### ISSUE TITLE
pyproj wheel broken on darwin, python 3.10, arm64 (m1 mac)

### ISSUE THREAD

**Issue by lazcamus** [pyproj4/pyproj#1024]
#### Code Sample, a copy-pastable example if possible
```shell
% pyenv global 3.10.2                
% pip3 install --no-cache pyproj
Collecting pyproj
  Downloading pyproj-3.3.0-cp310-cp310-macosx_10_9_universal2.whl (7.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.7/7.7 MB 49.8 MB/s eta 0:00:00
Requirement already satisfied: certifi in ./.pyenv/versions/3.10.2/lib/python3.10/site-packages (from pyproj) (2021.10.8)
Installing collected packages: pyproj
Successfully installed pyproj-3.3.0
[laz@lazyphus.local:~]
% python3 -m pyproj             
Traceback (most recent call last):
  File "/Users/laz/.pyenv/versions/3.10.2/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/Users/laz/.pyenv/versions/3.10.2/lib/python3.10/runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/Users/laz/.pyenv/versions/3.10.2/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/Users/laz/.pyenv/versions/3.10.2/lib/python3.10/site-packages/pyproj/__init__.py", line 49, in <module>
    import pyproj.network
  File "/Users/laz/.pyenv/versions/3.10.2/lib/python3.10/site-packages/pyproj/network.py", line 10, in <module>
    from pyproj._network import (  # noqa: F401 pylint: disable=unused-import
ImportError: dlopen(/Users/laz/.pyenv/versions/3.10.2/lib/python3.10/site-packages/pyproj/_network.cpython-310-darwin.so, 0x0002): tried: '/Users/laz/.pyenv/versions/3.10.2/lib/python3.10/site-packages/pyproj/_network.cpython-310-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/local/lib/_network.cpython-310-darwin.so' (no such file), '/usr/lib/_network.cpython-310-darwin.so' (no such file)
```

#### Problem description

_network.cpython-310-darwin.so is an x86_64 binary in a "universal" wheel ?

#### Installation method
pip

#### Workaround
```shell
% pip3 install --no-binary :all: pyproj                     
Collecting pyproj
  Using cached pyproj-3.3.0.tar.gz (217 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: certifi in ./.pyenv/versions/3.10.2/lib/python3.10/site-packages (from pyproj) (2021.10.8)
Building wheels for collected packages: pyproj
  Building wheel for pyproj (pyproject.toml) ... done
  Created wheel for pyproj: filename=pyproj-3.3.0-cp310-cp310-macosx_12_0_arm64.whl size=411966 sha256=7791dd6e57c2fcf59129c2d090ece6ee78549c16bb9dedb5d2731e8b9622b7fe
  Stored in directory: /Users/laz/Library/Caches/pip/wheels/f1/da/b3/2d2f699011a8e804c05fa59b59e52361e8afcd82af770d12fc
Successfully built pyproj
Installing collected packages: pyproj
Successfully installed pyproj-3.3.0
% python3 -m pyproj                    
usage: __main__.py [-h] [-v] {sync} ...

pyproj version: 3.3.0 [PROJ version: 8.2.1]

options:
  -h, --help     show this help message and exit
  -v, --verbose  Show verbose debugging version information.

commands:
  {sync}
```

**Comment by snowman2** [comment]
Closing for: https://github.com/pyproj4/pyproj-wheels/issues/46
