### ISSUE TITLE
3.6.0: pep517 build fails

### ISSUE THREAD

**Issue by kloczek** [pyproj4/pyproj#1311]
Looks like something is wrong with new release
```console
+ /usr/bin/python3 -sBm build -w --no-isolation
* Getting build dependencies for wheel...
<string>:10: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
    main()
  File "/usr/lib/python3.8/site-packages/pyproject_hooks/_in_process/_in_process.py", line 335, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "/usr/lib/python3.8/site-packages/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
    return hook(config_settings)
  File "/usr/lib/python3.8/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
    return self._get_build_requires(config_settings, requirements=['wheel'])
  File "/usr/lib/python3.8/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
    self.run_setup()
  File "/usr/lib/python3.8/site-packages/setuptools/build_meta.py", line 338, in run_setup
    exec(code, locals())
  File "<string>", line 76, in <module>
TypeError: 'type' object is not subscriptable

ERROR Backend subprocess exited when trying to invoke get_requires_for_build_wheel
```

**Comment by snowman2** [comment]
See: #1111

**Comment by kloczek** [comment]
If is only python 3.8 issue feel free to close this ticket because I'm moving soon to 3.9.

**Comment by snowman2** [comment]
I am fairly confident that this is a Python 3.8 issue. If you run into troubles with Python 3.9, feel free to open another issue.

**Comment by kloczek** [comment]
As I'm now in process of moving to 3.9 I'll accept your expertise.
Thx 👍
