### ISSUE TITLE
UnicodeEncodeError after pyinstaller

### ISSUE THREAD

**Issue by wyf115** [pyproj4/pyproj#139]
I wrote something for my work and I need to share it with my workmates. They have not installed Python and also don't know how to use. So I want to use Pyinstaller to convert my script. I used Pyinstaller. Running the exe file, it comes out like this. What should I do now?

Traceback (most recent call last):
  File "test1.py", line 11, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "c:\anaconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\geopandas\__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "c:\anaconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\geopandas\geoseries.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "c:\anaconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\pyproj\__init__.py", line 252, in <module>
  File "_proj.pyx", line 59, in _proj.set_datapath (_proj.c:887)
  File "_proj.pyx", line 370, in _proj._strencode (_proj.c:3939)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 5-8: ordinal not in range(128)

**Comment by micahcochran** [comment]
Does the install path have non-ascii characters in it?

**Comment by micahcochran** [comment]
Would PR #94 fix the issue?

**Comment by snowman2** [comment]
Feel free to reopen if this issue persists. Thanks for the report!
