### ISSUE TITLE
TransformerGroup does not handle cases where both the allow_superseded and always_xy user arguments is used

### ISSUE THREAD

**Issue by phaarnes** [pyproj4/pyproj#1464]
#### Ex. 1 TransformerGroup fails to list up available transformations when specifying both ``always_xy`` and ``allow_superseded ``

```python
from pyproj.transformer import TransformerGroup
TransformerGroup("EPSG:4230", "EPSG:4326", allow_superseded=True, always_xy=True).transformers
```

Outputs:
```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/pyproj/transformer.py", line 207, in __init__
    super().__init__(
  File "pyproj/_transformer.pyx", line 241, in pyproj._transformer._TransformerGroup.__init__
  File "pyproj/_transformer.pyx", line 602, in pyproj._transformer._Transformer._from_pj
  File "pyproj/_transformer.pyx", line 653, in pyproj._transformer._Transformer._init_from_crs
  File "pyproj/_transformer.pyx", line 359, in pyproj._transformer._Transformer._initialize_from_projobj
pyproj.exceptions.ProjError: Input is not a transformation.
```

#### Ex.2 TransformerGroup should return ``36`` available transformations when  ``allow_superseded `` not defined
```python
ct_lst = TransformerGroup("EPSG:4230", "EPSG:4326").transformers
print(len(ct_lst))
```

Outputs:
```python
36
```

#### Ex.3 TransformerGroup should return ``37`` available transformations when ``allow_superseded `` is set to ``True``
```python
ct_lst = TransformerGroup("EPSG:4230", "EPSG:4326", allow_superseded=True).transformers
print(len(ct_lst))
```

Outputs:
```python
37
```

ct_lst = TransformerGroup("EPSG:4230", "EPSG:4326", allow_superseded=True).transformers
print(len(ct_lst))

### Problem description
``TransformerGroup``  fails to a create a list of with all available transformation objects when the user set both ``always_xy`` and ``allow_superseded `` equals ``True``. 

### Environment Information
pyproj version 3.6.1
python 3.11

### Installation method
 pip wheel

**Comment by phaarnes** [comment]
An [issue](https://github.com/OSGeo/PROJ/issues/4343) is created in Proj GitHub repo.

**Comment by phaarnes** [comment]
I have investigated this further, and the root cause seems to be that Pyproj and ``TransformerGroup`` does not properly handle cases where `proj_normalize_for_visualization()` returns NULL.

One example that triggers this issue is the superseded transformation [EPSG:8047](https://epsg.org/concatenated-operation_8047/ED50-to-WGS-84-15.html?sessionkey=w0balagpl1). The issue raise when ``allow_superseeded==True`` in combinateion with ``always_xy=True``. This is a concatenated coordinate operation where the sub-operations have non-overlapping validity areas:

- [EPSG:1147 (ED50→ED87) - Norway N65 area](https://epsg.org/transformation_1147/ED50-to-ED87-2.html?sessionkey=qdvcdc3xyc)
- [EPSG:1146 (ED87→WGS84) - North Sea area](https://epsg.org/transformation_1146/ED87-to-WGS-84-1.html?sessionkey=w8gxl5skml) 

These don't have a common geographic intersection (see extents in the links above), which causes `proj_normalize_for_visualization()` to return NULL.

**On the pyproj side:** 

The crash was caused by pyproj not checking for NULL return from proj_normalize_for_visualization(). The code proceeded to use/destroy an invalid pointer. I have a possible fix ready that:

1. Properly checks for NULL return from proj_normalize_for_visualization()
2. Adds operations that cannot be normalized to unavailable_operations instead of crashing
3. Preserves the original pointer so it can still be used to create a CoordinateOperation


A PR is created with this fix for pyproj #1556.
