### ISSUE TITLE
pip install fails: nad2bin.c:2:19: fatal error: stdio.h: No such file or directory

### ISSUE THREAD

**Issue by shaharkadmiel** [pyproj4/pyproj#18]
```
pip install /Users/Shahar/Downloads/pyproj-master.zip 
Processing ./Downloads/pyproj-master.zip
    Complete output from command python setup.py egg_info:
    nad2bin.c:2:19: fatal error: stdio.h: No such file or directory
     #include <stdio.h>
                       ^
    compilation terminated.
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/var/folders/cp/d0fykvdx687ctsrklvnl4m6w0000gn/T/pip-Ey6WOM-build/setup.py", line 16, in <module>
        objects = cc.compile(['nad2bin.c', 'src/pj_malloc.c'])
      File "/Applications/Canopy.app/appdata/canopy-1.5.1.2730.macosx-x86_64/Canopy.app/Contents/lib/python2.7/distutils/ccompiler.py", line 574, in compile
        self._compile(obj, src, ext, cc_args, extra_postargs, pp_opts)
      File "/Applications/Canopy.app/appdata/canopy-1.5.1.2730.macosx-x86_64/Canopy.app/Contents/lib/python2.7/distutils/unixccompiler.py", line 122, in _compile
        raise CompileError, msg
    distutils.errors.CompileError: command 'gcc' failed with exit status 1

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /var/folders/cp/d0fykvdx687ctsrklvnl4m6w0000gn/T/pip-Ey6WOM-build
```

**Comment by micahcochran** [comment]
I little about Macs.  [This seems to be the answer.](http://stackoverflow.com/questions/19968744/imac-use-gcc-to-compile-c-or-c-file-stdio-h-no-such-file-or-directory)

**Comment by shaharkadmiel** [comment]
Thanks, I solved this problem but it proofed to be a little more complicated than just that. I had recently updated Xcode so command line tools had to be reinstalled. This meant that the license had to be re-agreed to and that the default compiler set by homebrew was overwritten. Everything was fixed once I reinstalled and upgraded to gcc5 via brew upgrade gcc. 

Thanks

**Comment by snowman2** [comment]
Glad to hear that you solved the problem. Side note, we have osx wheels for installation now for 2.1.0.
