### ISSUE TITLE
Invalid projection EPSG 54009 

### ISSUE THREAD

**Issue by brentonmallen1** [pyproj4/pyproj#341]
#### Code Sample, a copy-pastable example if possible

```python
coords = [(-97.59238135821987, 43.47456565304017),
 (-97.59244690469288, 43.47962399877412),
 (-97.59191951546768, 43.47962728271748),
 (-97.59185396090983, 43.47456565304017),
 (-97.59238135821987, 43.47456565304017)]

projection = partial(pyproj.transform, pyproj.Proj(init='epsg:4326'), pyproj.Proj(init='esri:54009'))
```

#### Problem description

When trying to re-project the polygon from EPSG:4326 to ESRI:54009, I get the following error:

```
---------------------------------------------------------------------------
CRSError                                  Traceback (most recent call last)
<ipython-input-33-26af3987d285> in <module>
      5  (-97.59238135821987, 43.47456565304017)]
      6 
----> 7 projection = partial(pyproj.transform, pyproj.Proj(init='epsg:4326'), pyproj.Proj(init='esri:54009'))
      8 shapely.ops.transform(projection, shapely.geometry.Polygon(coords)).area

~/miniconda3/envs/fs-ml/lib/python3.6/site-packages/pyproj/proj.py in __init__(self, projparams, preserve_units, **kwargs)
    145         '116.366 39.867'
    146         """
--> 147         self.crs = CRS.from_user_input(projparams if projparams is not None else kwargs)
    148         # make sure units are meters if preserve_units is False.
    149         if not preserve_units and "foot" in self.crs.axis_info[0].unit_name:

~/miniconda3/envs/fs-ml/lib/python3.6/site-packages/pyproj/crs.py in from_user_input(cls, value)
    389         if isinstance(value, _CRS):
    390             return value
--> 391         return cls(value)
    392 
    393     def get_geod(self):

~/miniconda3/envs/fs-ml/lib/python3.6/site-packages/pyproj/crs.py in __init__(self, projparams, **kwargs)
    258             raise CRSError("Invalid CRS input: {!r}".format(projparams))
    259 
--> 260         super(CRS, self).__init__(projstring)
    261 
    262     @classmethod

pyproj/_crs.pyx in pyproj._crs._CRS.__init__()

CRSError: Invalid projection: +init=esri:54009 +type=crs: (Internal Proj Error: proj_create: cannot expand +init=esri:54009 +type=crs)
```
I can't seem to figure out if I'm missing a definition or dependency of some kind.  Some insight would be appreciated.

Thanks!

#### Environment Information
 - pyproj version: `2.2.0`
 - PROJ version: `6.1.0`
 - PROJ data directory: `/Users/zoidberg/miniconda3/envs/fs-ml/share/proj`
 - Python version: `3.6.7 | packaged by conda-forge | (default, Feb 28 2019, 02:16:08)  [GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)]`
 - Operation System Information: `Darwin-18.6.0-x86_64-i386-64bit`
 - installation method: `conda`

**Comment by snowman2** [comment]
I tried it out and have a different issue:
```
>>> import pyproj
>>> pyproj.__version__
'2.2.0'
>>> pyproj.proj_version_str
'6.1.0'
>>> transformer = pyproj.Transformer.from_crs('epsg:4326', 'esri:54009')
>>> transformer
<Conversion Transformer: pipeline>
World_Mollweide
>>> transformer.definition
'proj=pipeline step proj=unitconvert xy_in=deg xy_out=rad step proj=moll lon_0=0 x_0=0 y_0=0 ellps=WGS84'
>>> transformer.transform(43.47456565304017, -97.59238135821987)
(inf, inf)
>>> transformer.transform(43.47456565304017, -97.59238135821987, errcheck=True) 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/snowal/miniconda3/envs/goldfinger/lib/python3.6/site-packages/pyproj/transformer.py", line 260, in transform
    errcheck=errcheck,
  File "pyproj/_transformer.pyx", line 189, in pyproj._transformer._Transformer._transform
pyproj.exceptions.ProjError: transform error: latitude or longitude exceeded limits
>>> transformer.transform(-97.59238135821987, 43.47456565304017, errcheck=True) 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/snowal/miniconda3/envs/goldfinger/lib/python3.6/site-packages/pyproj/transformer.py", line 260, in transform
    errcheck=errcheck,
  File "pyproj/_transformer.pyx", line 189, in pyproj._transformer._Transformer._transform
pyproj.exceptions.ProjError: transform error: latitude or longitude exceeded limits
>>> pyproj.CRS('esri:54009')
<Projected CRS: ESRI:54009>
Name: World_Mollweide
Axis Info [cartesian]:
- E[east]: Easting (metre)
- N[north]: Northing (metre)
Area of Use:
- name: World
- bounds: (-180.0, -90.0, 180.0, 90.0)
Coordinate Operation:
- name: World_Mollweide
- method: Mollweide
Datum: World Geodetic System 1984
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich

>>> pyproj.CRS("epsg:4326")
<Geographic 2D CRS: EPSG:4326>
Name: WGS 84
Axis Info [ellipsoidal]:
- Lat[north]: Geodetic latitude (degree)
- Lon[east]: Geodetic longitude (degree)
Area of Use:
- name: World
- bounds: (-180.0, -90.0, 180.0, 90.0)
Datum: World Geodetic System 1984
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich

```

**Comment by snowman2** [comment]
Nevermind, it was just an axis swap issue:
```
>>> import pyproj
>>> transformer = pyproj.Transformer.from_crs('epsg:4326', 'esri:54009')
>>> transformer.transform(-97.59238135821987, 43.47456565304017)
(-8011909.395609654, 5173947.778556228)
```

**Comment by snowman2** [comment]
This fails:
```
>>> transformer = pyproj.Transformer.from_crs('+init=epsg:4326', '+init=esri:54009')
...
pyproj.exceptions.CRSError: Invalid projection: +init=esri:54009 +type=crs: (Internal Proj Error: proj_create: cannot expand +init=esri:54009 +type=crs)
```

**Comment by snowman2** [comment]
@brentonmallen1, I am closing as I believe the solution to your problem has been found. If you need further assistance, feel free to reopen or add further comments.

**Comment by brentonmallen1** [comment]
@snowman2, that works great.  Thank you for your help!

**Comment by daniel-j-h** [comment]
@snowman2 any reason why the second version works while the first does not?

Also it seems like this is a breaking change since it used to work in old versions. Our users are hitting this in https://github.com/mapbox/robosat/issues/176 and I'd like to better understand this behavior before adding a fix on our end.

Thanks! :hugs:

**Comment by snowman2** [comment]
@daniel-j-h, the +init= syntax is deprecated. So, updating to avoid it is a good idea. I would recommend using `always_xy=True` in the transformer when updating.

Docs: https://pyproj4.github.io/pyproj/stable/gotchas.html#init-auth-auth-code-should-be-replaced-with-auth-auth-code
