### ISSUE TITLE
2.3.0 seg faults under Ubuntu

### ISSUE THREAD

**Issue by hyperknot** [pyproj4/pyproj#415]
#### Code Sample, a copy-pastable example if possible

A "Minimal, Complete and Verifiable Example" will make it much easier for maintainers to help you:
http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

Now that's tricky because I cannot do it. The seg fault very much depends on the input data, and it's part of a complex app. But with some input files 2.3.0 seg fault.

#### Problem description

Under 2.3.0 I can get the following using `python -X faulthandler`
```
Fatal Python error: Segmentation fault

Current thread 0x00007fa0f79c4700 (most recent call first):
  File "/opt/conda/lib/python3.7/site-packages/pyproj/crs.py", line 303 in __init__
  File "/opt/conda/lib/python3.7/site-packages/pyproj/crs.py", line 434 in from_user_input
  File "/opt/conda/lib/python3.7/site-packages/pyproj/proj.py", line 145 in __init__
  File "/opt/conda/lib/python3.7/site-packages/geopandas/geoseries.py", line 304 in to_crs
  File "/opt/conda/lib/python3.7/site-packages/geopandas/geodataframe.py", line 459 in to_crs
  ...
  File "<stdin>", line 1 in <module>
Segmentation fault (core dumped)
```

I've downgraded to 2.2.2 and I get a Python exception of the same lines, so it might be the same thing

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  ...
  File "/opt/conda/lib/python3.7/site-packages/geopandas/geodataframe.py", line 459, in to_crs
    geom = df.geometry.to_crs(crs=crs, epsg=epsg)
  File "/opt/conda/lib/python3.7/site-packages/geopandas/geoseries.py", line 304, in to_crs
    proj_in = pyproj.Proj(self.crs, preserve_units=True)
  File "/opt/conda/lib/python3.7/site-packages/pyproj/proj.py", line 147, in __init__
    self.crs = CRS.from_user_input(projparams if projparams is not None else kwargs)
  File "/opt/conda/lib/python3.7/site-packages/pyproj/crs.py", line 435, in from_user_input
    return cls(value)
  File "/opt/conda/lib/python3.7/site-packages/pyproj/crs.py", line 304, in __init__
    super(CRS, self).__init__(projstring)
  File "pyproj/_crs.pyx", line 1308, in pyproj._crs._CRS.__init__
  File "pyproj/_datadir.pyx", line 18, in pyproj._datadir.get_pyproj_context
  File "/opt/conda/lib/python3.7/site-packages/pyproj/datadir.py", line 99, in get_data_dir
    "Valid PROJ data directory not found. "
pyproj.exceptions.DataDirError: Valid PROJ data directory not found. Either set the path using the environmental variable PROJ_LIB or with `pyproj.datadir.set_data_dir`.
```

This is the same environment as I've detailed here: https://github.com/conda-forge/pyproj-feedstock/issues/47

#### Environment Information
after downgrade to 2.2.2
```

System:
    python: 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 21:52:21)  [GCC 7.3.0]
executable: /usr/bin/condapy
   machine: Linux-4.15.0-1037-gcp-x86_64-with-debian-stretch-sid

PROJ:
      PROJ: 6.1.1
  data dir: None

Python deps:
    pyproj: 2.2.2
       pip: 19.2.3
setuptools: 41.2.0
    Cython: None
     aenum: None
```

at 2.3.0
```

System:
    python: 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 21:52:21)  [GCC 7.3.0]
executable: /usr/bin/condapy
   machine: Linux-4.15.0-1037-gcp-x86_64-with-debian-stretch-sid

PROJ:
      PROJ: 6.1.1
  data dir: /opt/conda/share/proj

Python deps:
    pyproj: 2.3.0
       pip: 19.2.3
setuptools: 41.2.0
    Cython: None
```

#### Installation method
Conda in a Ubuntu 16.04 Docker image.

```
wget --quiet https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh && \
    /bin/bash ~/miniconda.sh -b -p /opt/conda && \
    conda update conda -y && \
    conda config --add channels conda-forge && \
    conda config --set channel_priority strict && \
    conda install \
        geopandas numexpr bottleneck
```

#### Conda environment information (if you installed with conda):

<br/>
Environment (<code>conda list</code>):
<details>

```
proj4                     6.1.1                hc80f0dc_1    conda-forge
pyproj                    2.3.0            py37h2fd02e8_0    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```

     active environment : None
       user config file : /root/.condarc
 populated config files : /root/.condarc
          conda version : 4.7.11
    conda-build version : not installed
         python version : 3.7.3.final.0
       virtual packages :
       base environment : /opt/conda  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/conda/pkgs
                          /root/.conda/pkgs
       envs directories : /opt/conda/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/4.7.11 requests/2.22.0 CPython/3.7.3 Linux/4.15.0-1037-gcp ubuntu/16.04.6 glibc/2.23
                UID:GID : 0:0
             netrc file : None
           offline mode : False
```
</details>

**Comment by snowman2** [comment]
Mind testing out: `pip install https://github.com/pyproj4/pyproj/archive/v2.3.1rc2.tar.gz`?

**Comment by hyperknot** [comment]
I've tried:

```
  ERROR: Complete output from command /opt/conda/bin/python /opt/conda/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpo1tk8s46:
  ERROR: Proj executable not found. Please set PROJ_DIR variable.
  ----------------------------------------
ERROR: Command "/opt/conda/bin/python /opt/conda/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpo1tk8s46" failed with error code 1 in /tmp/pip-req-build-bl_yrot_
```

I have no idea what is PROJ_DIR on a Conda Ubuntu install.

**Comment by snowman2** [comment]
Do you have your environment activated?

```
conda create -n pyproj proj python cython
conda activate pyproj
pip install https://github.com/pyproj4/pyproj/archive/v2.3.1rc2.tar.gz

```

**Comment by hyperknot** [comment]
The pip install in that one worked, but I don't know why is my geopandas environment not working: https://github.com/conda-forge/geopandas-feedstock/issues/63

**Comment by snowman2** [comment]
> The pip install in that one worked, but I don't know why is my geopandas environment not working: [conda-forge/geopandas-feedstock#63](https://github.com/conda-forge/geopandas-feedstock/issues/63)

Did you activate your geopandas conda environment?
```
conda create -n test  geopandas numexpr bottleneck
conda activate test
pip install --ignore-installed https://github.com/pyproj4/pyproj/archive/v2.3.1rc2.tar.gz
```

**Comment by snowman2** [comment]
You don't seem to be using the conda environment, how about:
```
PROJ_DIR=/opt/conda pip install --ignore-installed https://github.com/pyproj4/pyproj/archive/v2.3.1rc2.tar.gz
```

**Comment by hyperknot** [comment]
OK, I think you've found out what is happening in conda-forge/geopandas-feedstock#63, that is the local environment and the global environment are not behaving the same. If I install the dependencies in a local environment the bug is not present.

Which is not helping us, as I won't be able to reproduce the bug on the updated build.

**Comment by hyperknot** [comment]
I was able to create a minimal reproducible Python code for the seg fault:

```

import geopandas
import pandas as pd
import utm
from shapely.geometry import Point


def find_best_crs(lat, lon):
    utm_zone = utm.from_latlon(lat, lon)[2]
    return f'+proj=utm +zone={utm_zone} +ellps=WGS84 +datum=WGS84 +units=m +no_defs'


d = {'lat': [48], 'lon': [17]}
df = pd.DataFrame(data=d)

df['Coordinates'] = list(zip(df.lon, df.lat))
df['Coordinates'] = df['Coordinates'].apply(Point)

gdf = geopandas.GeoDataFrame(df, geometry='Coordinates', crs={'init': 'epsg:4326'})

crs_text = find_best_crs(48, 17)

gdf = gdf.to_crs(crs_text)
```

**Comment by snowman2** [comment]
Can you test this out:
```
RUN wget --quiet https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh && \
    /bin/bash ~/miniconda.sh -b -p /opt/conda && \
    /opt/conda/bin/conda update conda -y && \
    /opt/conda/bin/conda config --add channels conda-forge && \
    /opt/conda/bin/conda config --set channel_priority strict && \
    /opt/conda/bin/conda install \
        geopandas numexpr bottleneck cython && \
   /opt/conda/bin/conda activate && pip install --ignore-in/opt/conda/bin/condastalled https://github.com/pyproj4/pyproj/archive/v2.3.1rc2.tar.gz
```

**Comment by hyperknot** [comment]
I'll test it in a moment, but just now I wanted to report that the fix didn't work, I got a segfault as well, using:

```
PROJ_DIR=/opt/conda pip install --ignore-installed https://github.com/pyproj4/pyproj/archive/v2.3.1rc2.tar.gz
```

**Comment by snowman2** [comment]
Does this segfault?
```
python -c “import pyproj; pyproj.show_versions()”
```

**Comment by hyperknot** [comment]
> Does this segfault?
> 
> ```
> python -c “import pyproj; pyproj.show_versions()”
> ```

No that doesn't.

I've created a super minimal repro case:

Dockerfile
```
FROM ubuntu:16.04

RUN apt-get update && apt-get install -y wget

RUN wget --quiet https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh && \
    /bin/bash ~/miniconda.sh -b -p /opt/conda && \
    /opt/conda/bin/conda update conda -y && \
    /opt/conda/bin/conda config --add channels conda-forge && \
    /opt/conda/bin/conda config --set channel_priority strict


RUN /opt/conda/bin/conda install \
        geopandas numexpr bottleneck

RUN apt-get update && apt-get install -y --no-install-recommends build-essential

RUN PROJ_DIR=/opt/conda /opt/conda/bin/pip install --ignore-installed https://github.com/pyproj4/pyproj/archive/v2.3.1rc2.tar.gz


RUN /opt/conda/bin/python -c 'import fiona'

RUN /opt/conda/bin/python -c 'import pyproj; pyproj.show_versions()'

ADD test.py .
RUN /opt/conda/bin/python test.py
```

test.py
```
import geopandas
import pandas as pd
from shapely.geometry import Point

d = {'lat': [48], 'lon': [17]}
df = pd.DataFrame(data=d)

df['Coordinates'] = list(zip(df.lon, df.lat))
df['Coordinates'] = df['Coordinates'].apply(Point)

gdf = geopandas.GeoDataFrame(df, geometry='Coordinates', crs={'init': 'epsg:4326'})

gdf = gdf.to_crs('+proj=utm +zone=33 +ellps=WGS84 +datum=WGS84 +units=m +no_defs')
```

**Comment by hyperknot** [comment]
The output is:

```
Step 7/10 : RUN /opt/conda/bin/python -c 'import fiona'
 ---> Running in 319c2eee4b31
proj_create: Open of /opt/conda/share/proj failed
proj_create: init=epsg:/init=IGNF: syntax not supported in non-PROJ4 emulation mode
proj_create: Open of /opt/conda/share/proj failed
proj_create: init=epsg:/init=IGNF: syntax not supported in non-PROJ4 emulation mode
Removing intermediate container 319c2eee4b31
 ---> 0be54f8fe36d
Step 8/10 : RUN /opt/conda/bin/python -c 'import pyproj; pyproj.show_versions()'
 ---> Running in d87964f1e210

System:
    python: 3.7.3 | packaged by conda-forge | (default, Jul  1 2019, 21:52:21)  [GCC 7.3.0]
executable: /opt/conda/bin/python
   machine: Linux-4.15.0-1037-gcp-x86_64-with-debian-stretch-sid

PROJ:
      PROJ: 6.1.1
  data dir: /opt/conda/share/proj

Python deps:
    pyproj: 2.3.1
       pip: 19.2.3
setuptools: 41.2.0
    Cython: None
Removing intermediate container d87964f1e210
 ---> b278f61b463d
Step 9/10 : ADD test.py .
 ---> dd013791a407
Step 10/10 : RUN /opt/conda/bin/python test.py
 ---> Running in c9041916117b
proj_create: Open of /opt/conda/share/proj failed
proj_create: init=epsg:/init=IGNF: syntax not supported in non-PROJ4 emulation mode
proj_create: Open of /opt/conda/share/proj failed
proj_create: init=epsg:/init=IGNF: syntax not supported in non-PROJ4 emulation mode
Segmentation fault (core dumped)
The command '/bin/sh -c /opt/conda/bin/python test.py' returned a non-zero code: 139
```

**Comment by hyperknot** [comment]
Updated ^^^ with `python -X faulthandler`

**Comment by snowman2** [comment]
Hmmm, if the data directory is found, I am not entirely convinced that the issue is pyproj. But, I could be wrong.

**Comment by snowman2** [comment]
Can you try some debugging done in #368?

**Comment by hyperknot** [comment]
Here are some results:

```
RUN /opt/conda/bin/conda install 'pyproj < 2.3'

Traceback (most recent call last):
  File "test.py", line 13, in <module>
    gdf = gdf.to_crs('+proj=utm +zone=33 +ellps=WGS84 +datum=WGS84 +units=m +no_defs')
  File "/opt/conda/lib/python3.7/site-packages/geopandas/geodataframe.py", line 459, in to_crs
    geom = df.geometry.to_crs(crs=crs, epsg=epsg)
  File "/opt/conda/lib/python3.7/site-packages/geopandas/geoseries.py", line 304, in to_crs
    proj_in = pyproj.Proj(self.crs, preserve_units=True)
  File "/opt/conda/lib/python3.7/site-packages/pyproj/proj.py", line 147, in __init__
    self.crs = CRS.from_user_input(projparams if projparams is not None else kwargs)
  File "/opt/conda/lib/python3.7/site-packages/pyproj/crs.py", line 435, in from_user_input
    return cls(value)
  File "/opt/conda/lib/python3.7/site-packages/pyproj/crs.py", line 304, in __init__
    super(CRS, self).__init__(projstring)
  File "pyproj/_crs.pyx", line 1308, in pyproj._crs._CRS.__init__
  File "pyproj/_datadir.pyx", line 18, in pyproj._datadir.get_pyproj_context
  File "/opt/conda/lib/python3.7/site-packages/pyproj/datadir.py", line 99, in get_data_dir
    "Valid PROJ data directory not found. "
pyproj.exceptions.DataDirError: Valid PROJ data directory not found. Either set the path using the environmental variable PROJ_LIB or with `pyproj.datadir.set_data_dir`.
```

However 
```
RUN /opt/conda/bin/pip install 'pyproj < 2.3 '
```
=> everything is fine, no errors.

**Comment by hyperknot** [comment]
```
RUN /opt/conda/bin/conda install 'pyproj < 2.3'
RUN PROJ_LIB=/opt/conda/share/proj /opt/conda/bin/python -X faulthandler test.py
```

works, so does 
```
RUN PROJ_LIB=/opt/conda/share/proj /opt/conda/bin/python -X faulthandler test.py
```
with PyProj 2.3.0.

**Comment by hyperknot** [comment]
So I can conclude there are exactly two bugs here:
1. If PROJ_LIB is not found then 2.3.0 Segfaults, instead of terminating with a message like 2.2 does.
2. PROJ_LIB needs to be specified in the newer Conda install. That effect Fiona, etc. as well.

**Comment by snowman2** [comment]
I am wondering if the default comes from Fiona. Using epsg uses Fiona to get the epsg: https://github.com/geopandas/geopandas/blob/29add0a735b00dc20c79e0fccc8e6a775c4997b0/geopandas/geoseries.py#L397

And there are errors with Fiona about the data directory on import. Setting PROJ_LIB fixes those errors.

You can prove my hypothesis wrong by passing in `crs='+init=epsg:3857'` into to_crs instead of epsg=3857.

**Comment by snowman2** [comment]
Nevermind, your test is using CRS.

**Comment by snowman2** [comment]
The difference with pyproj 2.3.0 is that it finds the data directory without PROJ_LIB set as shown by it being set in `pyproj.show_versions()`. What happens if you only replace the Fiona wheel?

**Comment by hyperknot** [comment]
Still the same segfault. The Fiona pip reinstall fixes the `proj_create` lines from Fiona. The pyproj pip reinstall fixes the PROJ_LIB segfault from Pyproj.

**Comment by snowman2** [comment]
Probably a conda issue, but probably good to double check.

**Comment by hyperknot** [comment]
So the Conda issue was as simple as not having PROJ_LIB exported. Exporting PROJ_LIB makes the seg fault not happen.

However the seg fault is still present, I mean the fact that:
- 2.2 was able to write a nice message and throw a python exception when PROJ_LIB was not present
- 2.3 is not able to do so, it just silently terminates with the seg fault.

**Comment by hyperknot** [comment]
So I'd conclude that the issue is: When PROJ_LIB is not present correctly, 2.3.0 terminates with a seg fault, instead of throwing an error message like 2.2 did.

**Comment by snowman2** [comment]
That isn't necessarily what the issue is. https://pyproj4.github.io/pyproj/stable/api/datadir.html#pyproj.datadir.get_data_dir

According to your output, `pyproj==2.3.0` found the data directory:
```
RUN /opt/conda/bin/python -c 'import pyproj; pyproj.show_versions()'
 ...
PROJ:
      PROJ: 6.1.1
  data dir: /opt/conda/share/proj
...
```
This raised an exception in pyproj==2.2.2 because it did not search `sys.prefix`:https://pyproj4.github.io/pyproj/v2.2.2rel/api/datadir.html#pyproj.datadir.get_data_dir and therefore did not find the data directory without PROJ_LIB set.

I am just not sure what the problem is yet - need time to debug it.

**Comment by snowman2** [comment]
I think I found the solution in #419. Will make a release candidate to test soon.

**Comment by snowman2** [comment]
can you try with : `pip install --ignore-installed https://github.com/pyproj4/pyproj/archive/v2.3.1rc3.tar.gz`?

**Comment by dazza-codes** [comment]
@snowman2 - is there any way this fix could be added to a patch on a 2.2.x release?  The conda-forge ecosystem will not install geopandas==0.5.* with pyproj==2.3.*

**Comment by snowman2** [comment]
@dazza-codes, I would recommend raising an issue about it here first: https://github.com/conda-forge/geopandas-feedstock. I think that would probably be an easier path forward.

**Comment by jorisvandenbossche** [comment]
> The conda-forge ecosystem will not install geopandas==0.5.* with pyproj==2.3.*

@dazza-codes can you clarify what doesn't work?

**Comment by dazza-codes** [comment]
There is or was something weird in the conda env install process that led to me to this and similar issues about failure to open the proj CRS database.  The solution seems to be using specific conda-forge config options on the new conda-env.  e.g.

```
$ conda create -y -n tmp \
      --channel conda-forge \
      --override-channels \
      python=3.7
$ conda activate tmp

# these config options could be important
$ conda config --env --add channels conda-forge
$ conda config --env --set channel_priority strict

$ conda install geopandas==0.5.* pyproj==2.3.* gdal==2.4.2
  environment location: /opt/conda/envs/tmp
  added / updated specs:
    - gdal==2.4.2
    - geopandas=0.5
    - pyproj=2.3 # with proj4-6.1.1
```
