### ISSUE TITLE
Usage of Potsdam Datum not possible in pyproj.Proj()

### ISSUE THREAD

**Issue by neumannd** [pyproj4/pyproj#425]
Maybe related to #198 

#### Code Sample, a copy-pastable example if possible

Minimal, Complete and Verifiable Example:

```python
# import pyproj
import pyproj as pp

# generate a projection function
my_proj = pp.Proj("+proj=lcc +lat_1=30 +lat_2=60 +lat_0=30 +lon_0=10 +ellps=bessel +datum=potsdam +x_0=-1920000.0 +y_0=-3200000.0")

## ERROR:
# Traceback (most recent call last):
#   File "<stdin>", line 1, in <module>
#   File "/opt/python/anaconda3/lib/python3.7/site-packages/pyproj/proj.py", line 147, in __init__
#     self.crs = CRS.from_user_input(projparams if projparams is not None else kwargs)
#   File "/opt/python/anaconda3/lib/python3.7/site-packages/pyproj/crs.py", line 429, in from_user_input
#     return cls(value)
#   File "/opt/python/anaconda3/lib/python3.7/site-packages/pyproj/crs.py", line 298, in __init__
#     super(CRS, self).__init__(projstring)
#   File "pyproj/_crs.pyx", line 1292, in pyproj._crs._CRS.__init__
# pyproj.exceptions.CRSError: Invalid projection: +proj=lonlat +ellps=bessel +datum=potsdam +type=crs: (Internal Proj Error: proj_create: unknown datum potsdam)

# trying another projection
my_proj = pp.Proj("+proj=lonlat +ellps=bessel +datum=potsdam")
## the same error
```

#### Problem description

The function `pyproj.Proj()` throws an error if the `potsdam` datum is used. The command line tool `proj` works fine (see code below). The datum and ellipsoid names where copied from the output of `proj -ld`.

```
# command line PROJ lists the potsdam datum as possible datum:
proj -ld
# __datum_id__ __ellipse___ __definition/comments______________________________
#        WGS84 WGS84        towgs84=0,0,0                 
#       GGRS87 GRS80        towgs84=-199.87,74.79,246.62  
#                           Greek_Geodetic_Reference_System_1987
#        NAD83 GRS80        towgs84=0,0,0                 
#                           North_American_Datum_1983
#        NAD27 clrk66       nadgrids=@conus,@alaska,@ntv2_0.gsb,@ntv1_can.dat
#                           North_American_Datum_1927
#      potsdam bessel       nadgrids=@BETA2007.gsb        
#                           Potsdam Rauenberg 1950 DHDN
#     carthage clrk80ign    towgs84=-263.0,6.0,431.0      
#                           Carthage 1934 Tunisia
# hermannskogel bessel       towgs84=577.326,90.129,463.919,5.137,1.474,5.297,2.4232
#                           Hermannskogel
#        ire65 mod_airy     towgs84=482.530,-130.596,564.557,-1.042,-0.214,-0.631,8.15
#                           Ireland 1965
#       nzgd49 intl         towgs84=59.47,-5.04,187.44,0.47,-0.1,1.024,-4.5993
#                           New Zealand Geodetic Datum 1949
#       OSGB36 airy         towgs84=446.448,-125.157,542.060,0.1502,0.2470,0.8421,-20.4894
#                           Airy 1830

# command line PROJ can handle the PROJ-string
proj +proj=lcc +lat_1=30 +lat_2=60 +lat_0=30 +lon_0=10 +ellps=bessel +datum=potsdam +x_0=-1920000.0 +y_0=-3200000.0 -r <<EOF
+45.25919444444 111.5
EOF
# > 3871770.61	2713138.72
```

#### Expected Output

No error.

#### Environment Information

 - Output from: `python -c "import pyproj; pyproj.show_versions()"`

```
System:
    python: 3.7.3 (default, Mar 27 2019, 22:11:17)  [GCC 7.3.0]
executable: /opt/python/anaconda3/bin/python
   machine: Linux-5.0.0-27-generic-x86_64-with-debian-buster-sid

PROJ:
      PROJ: 6.1.0
  data dir: /opt/python/anaconda3/share/proj

Python deps:
    pyproj: 2.2.1
       pip: 19.0.3
setuptools: 40.8.0
    Cython: 0.29.6
     aenum: None
```

#### Installation method
 - conda, pip wheel, from source, etc...

```
conda install -c conda-forge pyproj 
```

#### Conda environment information (if you installed with conda):

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list | grep -E "proj|aenum"
anaconda-project          0.8.2                    py37_0  
proj4                     6.1.0                he751ad9_2    conda-forge
pyproj                    2.2.1            py37hc44880f_0    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
     active environment : base
    active env location : /opt/python/anaconda3
            shell level : 1
       user config file : /home/k204221/.condarc
 populated config files : /home/k204221/.condarc
          conda version : 4.7.11
    conda-build version : 3.18.7
         python version : 3.7.3.final.0
       virtual packages : 
       base environment : /opt/python/anaconda3  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /opt/python/anaconda3/pkgs
                          /home/k204221/.conda/pkgs
       envs directories : /opt/python/anaconda3/envs
                          /home/k204221/.conda/envs
               platform : linux-64
             user-agent : conda/4.7.11 requests/2.21.0 CPython/3.7.3 Linux/5.0.0-27-generic ubuntu/18.04.3 glibc/2.27
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False
```
</details>

**Comment by snowman2** [comment]
Likely related: https://github.com/OSGeo/PROJ/pull/1573

**Comment by neumannd** [comment]
Seems to be related. The workaround mentioned in [OSGeo/PROJ#1573](https://github.com/OSGeo/PROJ/pull/1573) solves the issue. Thanks for looking it up.

```
my_proj = pp.Proj("+proj=lcc +lat_1=30 +lat_2=60 +lat_0=30 +lon_0=10 +ellps=bessel +nadgrids=@BETA2007.gsb +x_0=-1920000.0 +y_0=-3200000.0")
# no error
my_proj(9.976251, 53.566790)
# > (-1921455.944916521, -649348.6238974421)
```

Should I close this issue?

**Comment by snowman2** [comment]
Closing as it is PROJ related.
