### ISSUE TITLE
Has pyproj.crs accidentally removed from the pyproj?

### ISSUE THREAD

**Issue by OldSubSailor** [pyproj4/pyproj#521]
**Has pyproj.crs accidentally removed from the pyproj?
I think that pyproj was correctly installed:
Building wheels for collected packages: pyproj
Building wheel for pyproj (PEP 517) ... done
Created wheel for pyproj: filename=pyproj-2.4.2.post1-cp38-cp38-macosx_10_9_x86_64.whl size=385567 sha256=eeec09d7d31b88693003831cb3950bb675b5c95ec80822371aed705ac2ad7d58
Stored in directory: /private/var/folders/81/dknbj9t122v60nzlhfx5sspc0000gn/T/pip-ephem-wheel-cache-96kl54dd/wheels/cd/4d/b5/3ee84377669dbd035549164debd46ef4b88baabb8c99f8900e
Successfully built pyproj

This error has suddenly appeared when trying to run Ortho4xp; it was working fine until I reinstalled files last night.

from pyproj.crs import CRS
Traceback (most recent call last):
File "", line 1, in 
File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyproj/init.py", line 81, in 
from pyproj.crs import CRS # noqa: F401
ModuleNotFoundError: No module named 'pyproj.crs'**

**Comment by snowman2** [comment]
I wonder if your environment is corrupted?

```
>>> from pyproj.crs import CRS
>>> import pyproj
>>> pyproj.show_versions()
pyproj info:
    pyproj: 2.4.2.post1
      PROJ: 6.2.1
  data dir: ../miniconda/envs/py38/lib/python3.8/site-packages/pyproj/proj_dir/share/proj

System:
    python: 3.8.1 | packaged by conda-forge | (default, Jan  5 2020, 20:58:18)  [GCC 7.3.0]
executable: ../miniconda/envs/py38/bin/python
   machine: Linux-4.15.0-74-generic-x86_64-with-glibc2.10

Python deps:
       pip: 20.0.2
setuptools: 45.1.0.post20200119
    Cython: None
```

**Comment by OldSubSailor** [comment]
Thank you for your reply
If I use pip3 or brew to get pyproj, it says that it is installed. However, if I understand your email correctly, you wanted me to enter python and run as shown.
Here is what I got:
Last login: Mon Jan 27 10:35:48 on ttys000
But what do I know? % hiss                
Python 3.8.1 (v3.8.1:1b293b6006, Dec 18 2019, 14:08:53) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from pyproj.crs import CRS
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyproj/__init__.py", line 81, in <module>
    from pyproj.crs import CRS  # noqa: F401
ModuleNotFoundError: No module named 'pyproj.crs'
>>> import pyproj
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pyproj/__init__.py", line 81, in <module>
    from pyproj.crs import CRS  # noqa: F401
ModuleNotFoundError: No module named 'pyproj.crs'
>>> pyproj.show_versions()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'pyproj' is not defined
>>> 

I am using macOS Catalina. I also was wondering about things being corrupted. Last night when I tried to open IDLE by double clicking on the icon, it would not open.


Trav

**Comment by OldSubSailor** [comment]
I reinstalled macOS Catalina and get the same failed results.

Isn’t pyproj supposed to include pyproj.crs? I believe it did in the past. 
A C program is like a fast dance on a newly waxed dance floor by people carrying razors.  -W.R.

And now for something completely different. -M.P

**Comment by snowman2** [comment]
> Isn’t pyproj supposed to include pyproj.crs?

Yes it is. I installed the same version you had with python 3.8 and it worked for me. So, it must be something different. Possibly OS related, but I am not sure.

Can you try creating a new python virtual environment and trying it out there?

```bash
python3.8 -m venv pyproj_test
. pyproj_test/bin/activate
python -m pip install pyproj
```

**Comment by OldSubSailor** [comment]
Thank you for your reply,
I believe that this is the script line that the Ortho4XP uses to get pyproj:

pip3 install git+https://github.com/jswhit/pyproj.git <git+https://github.com/jswhit/pyproj.git>

However, I never could locate pyproj.crs

Then I was clued in to entering 

pip3 install  pyproj==1.9.6

After which I had pyproj.crs again (and working)

I was also able to do this with 2.4.1 & 2.4.2

At this time, I am using Python 3.7.6 that was installed when I reinstalled Xcode.

I am sorry, butI do not know what a python virtual environment is. 

Trav

**Comment by snowman2** [comment]
I realized that it was in the master branch after your last comment. I added a fix in #522.

**Comment by OldSubSailor** [comment]
Very cool, thank you for your help.

A C program is like a fast dance on a newly waxed dance floor by people carrying razors.  -W.R.

**Comment by OldSubSailor** [comment]
One final question. Were is pyproj stored? I can't find it via the unix search commands that I know.
Thank you

**Comment by snowman2** [comment]
You should see the base path to site-packages with `pip show pyproj`. A `pyproj` directory should be stored there.

**Comment by OldSubSailor** [comment]
Thank you again. 


A C program is like a fast dance on a newly waxed dance floor by people carrying razors.  -W.R.

And now for something completely different. -M.P

**Comment by OldSubSailor** [comment]
Gad, I hate all this bothering you, but is this something that needs to be addressed, and by whom?

/usr/local/lib/python3.7/site-packages/pyproj/crs.py:77: FutureWarning: '+init=<authority>:<code>' syntax is deprecated. '<authority>:<code>' is the preferred initialization method.
  return _prepare_from_string(" ".join(pjargs))

**Comment by jorisvandenbossche** [comment]
That's a deprecation warning that is being raised on purpose by pyproj. So either you are using pyproj directly and then you will need to address it, or either you are using it through another library (eg geopandas, and in that case the next geopandas release will fix that)

**Comment by OldSubSailor** [comment]
If you have the time sometime, and it is not too complicated, could you explain what that means?
Thank you

**Comment by snowman2** [comment]
I would recommend reading:
- https://pyproj4.github.io/pyproj/stable/gotchas.html#init-auth-auth-code-should-be-replaced-with-auth-auth-code
- https://pyproj4.github.io/pyproj/stable/gotchas.html#axis-order-changes-in-proj-6

**Comment by PythonMATLABGIS** [comment]
I had the same error. What should I do? Thanks!
![image](https://user-images.githubusercontent.com/62207987/90210031-8d0ccc00-de1f-11ea-9952-7d01b5969617.png)

**Comment by snowman2** [comment]
@PythonMATLABGIS, what pyproj version are you using? The CRS class was introduced in version 2.
