### ISSUE TITLE
pyproj.CRS.from_epsg() not working

### ISSUE THREAD

**Issue by jheilbro** [pyproj4/pyproj#523]
I'm using the following versions of pyproj and Python: 
```
pyproj.show_versions()
pyproj info:
    pyproj: 2.4.2.post1
      PROJ: 6.3.0
  data dir: /Users/.../miniconda3/share/proj
System:
    python: 3.7.6 | packaged by conda-forge | (default, Jan  7 2020, 22:05:27)  [Clang 9.0.1 ]
executable: /Users/.../miniconda3/envs/Mort_MktPwr/bin/python
   machine: Darwin-19.2.0-x86_64-i386-64bit
Python deps:
       pip: 20.0.2
setuptools: 45.1.0.post20200119
    Cython: None
```

I can't seem to construct simple CRS, as follows: 

```
pyproj.CRS.from_epsg(4326)
Traceback (most recent call last):
...
  File "pyproj/_crs.pyx", line 1738, in pyproj._crs._CRS.__init__
pyproj.exceptions.CRSError: Invalid projection: epsg:4326: (Internal Proj Error: proj_create: cannot build geodeticCRS 4326: SQLite error on SELECT name, ellipsoid_auth_name, ellipsoid_code, prime_meridian_auth_name, prime_meridian_code, area_of_use_auth_name, area_of_use_code, publication_date, deprecated FROM geodetic_datum WHERE auth_name = ? AND code = ?: no such column: publication_date)
```

Ultimately, this is preventing me from changing CRS in GeoPandas. 

```
dfTrans.to_crs('epsg:4326')
Traceback (most recent call last):
...
  File "pyproj/_crs.pyx", line 1738, in pyproj._crs._CRS.__init__
pyproj.exceptions.CRSError: Invalid projection: epsg:4326: (Internal Proj Error: proj_create: cannot build geodeticCRS 4326: SQLite error on SELECT name, ellipsoid_auth_name, ellipsoid_code, prime_meridian_auth_name, prime_meridian_code, area_of_use_auth_name, area_of_use_code, publication_date, deprecated FROM geodetic_datum WHERE auth_name = ? AND code = ?: no such column: publication_date)
```

I'm not very familiar with these packages, so I could be missing something simple. Any suggestions?

**Comment by snowman2** [comment]
Mind giving the output from `conda list proj` and `conda list sqlite`?
```
conda list proj
# packages in environment at ../miniconda/envs/pjtst:
#
# Name                    Version                   Build  Channel
proj                      6.3.0                hc80f0dc_0    conda-forge
pyproj                    2.4.2.post1      py37h8ff28aa_1    conda-forge
```
```
conda list sqlite
# packages in environment at ../miniconda/envs/pjtst:
#
# Name                    Version                   Build  Channel
sqlite                    3.30.1               hcee41ef_0    conda-forge
```
It worked for me on linux with the `conda-forge` channel:
```
conda create -n pjtst python=3.7 proj=6.3 pyproj
conda activate pjtst
```
```
>>> from pyproj import CRS
>>> cc = CRS.from_epsg(4326)
>>> cc
<Geographic 2D CRS: EPSG:4326>
Name: WGS 84
Axis Info [ellipsoidal]:
- Lat[north]: Geodetic latitude (degree)
- Lon[east]: Geodetic longitude (degree)
Area of Use:
- name: World
- bounds: (-180.0, -90.0, 180.0, 90.0)
Datum: World Geodetic System 1984
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich

>>> import pyproj
>>> pyproj.show_versions()
pyproj info:
    pyproj: 2.4.2.post1
      PROJ: 6.3.0
  data dir: .../miniconda/envs/pjtst/share/proj

System:
    python: 3.7.6 | packaged by conda-forge | (default, Jan  7 2020, 22:33:48)  [GCC 7.3.0]
executable: ../miniconda/envs/pjtst/bin/python
   machine: Linux-4.15.0-74-generic-x86_64-with-debian-buster-sid

Python deps:
       pip: 20.0.2
setuptools: 45.1.0.post20200119
    Cython: None

```

**Comment by jheilbro** [comment]
Thanks for taking a look at this. They are below. They seem to look like yours. 

```
 conda list proj
# packages in environment at .../miniconda3/envs/Mort_MktPwr:
#
# Name                    Version                   Build  Channel
proj                      6.3.0                h773a61f_0    conda-forge
pyproj                    2.4.2.post1      py37hf8af742_1    conda-forge
 conda list sqlite
# packages in environment at .../miniconda3/envs/Mort_MktPwr:
#
# Name                    Version                   Build  Channel
sqlite                    3.30.1               h93121df_0    conda-forge

```

**Comment by jheilbro** [comment]
(I can follow your instructions, though, and it seems to work fine. Let me see about resetting my environment.)

**Comment by jheilbro** [comment]
It seems to be something specifically to do with working in PyCharm. Otherwise, there is no problem. Anyway, thanks for the sanity check.
