### ISSUE TITLE
class Proj throws errors when other keywords are in constructor

### ISSUE THREAD

**Issue by mwtoews** [pyproj4/pyproj#584]
Out in the wild, I see code snippets like this:
```python
from pyproj import Proj

crs = Proj('epsg:4326', preserve_units=True, errcheck=True)
```
#### Problem description
With pyproj<=2.5.0 there is no issue with this line, and I would guess `errcheck` was put here by the upstream user as it seems to be [documented](http://pyproj4.github.io/pyproj/stable/api/proj.html#pyproj-proj). I suspect these keyword options (including `inverse`) are actually ignored, as I don't see any difference with the behaviour of the resulting object.

With pyproj==2.6.0, any keyword option is passed to PROJ, e.g. `errcheck=True`, `inverse=True` or `bazoom=True` throws:
```
>>> pyproj.Proj('epsg:4326', preserve_units=True, errcheck=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/venv/lib/python3.6/site-packages/pyproj/proj.py", line 126, in __init__
    self.crs = CRS.from_user_input(projparams, **kwargs)
  File "/tmp/venv/lib/python3.6/site-packages/pyproj/crs/crs.py", line 440, in from_user_input
    return CRS(value, **kwargs)
  File "/tmp/venv/lib/python3.6/site-packages/pyproj/crs/crs.py", line 296, in __init__
    super().__init__(projstring)
  File "pyproj/_crs.pyx", line 2338, in pyproj._crs._CRS.__init__
pyproj.exceptions.CRSError: Invalid projection: epsg:4326 +errcheck: (Internal Proj Error: proj_create: crs not found)
```
or similar, but different error:
```
>>> pyproj.Proj('epsg:4326', preserve_units=True, errcheck=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/venv/lib/python3.6/site-packages/pyproj/proj.py", line 126, in __init__
    self.crs = CRS.from_user_input(projparams, **kwargs)
  File "/tmp/venv/lib/python3.6/site-packages/pyproj/crs/crs.py", line 440, in from_user_input
    return CRS(value, **kwargs)
  File "/tmp/venv/lib/python3.6/site-packages/pyproj/crs/crs.py", line 293, in __init__
    projkwargs = _prepare_from_dict(kwargs, allow_json=False)
  File "/tmp/venv/lib/python3.6/site-packages/pyproj/crs/crs.py", line 53, in _prepare_from_dict
    return _prepare_from_string(" ".join(pjargs))
  File "/tmp/venv/lib/python3.6/site-packages/pyproj/crs/crs.py", line 58, in _prepare_from_string
    raise CRSError("CRS is empty or invalid: {!r}".format(in_crs_string))
pyproj.exceptions.CRSError: CRS is empty or invalid: ''
```

#### Expected Output
Either use documented keywords (like `errcheck`) or perhaps a warning should be shown: "ignored keywords: {'bazoom': True}". As previous version did not throw an exceptions, new versions should also avoid throwing exceptions. If these keywords are no longer accepted, then remove them from the documentation, where appropriate.

#### Environment Information
 - Output from: `python -m pyproj -v`
<details>

```
pyproj info:
    pyproj: 2.6.0
      PROJ: 6.3.1
  data dir: /tmp/venv/lib/python3.6/site-packages/pyproj/proj_dir/share/proj

System:
    python: 3.6.9 (default, Nov  7 2019, 10:44:02)  [GCC 8.3.0]
executable: /tmp/venv/bin/python
   machine: Linux-4.15.0-91-generic-x86_64-with-Ubuntu-18.04-bionic

Python deps:
       pip: 9.0.1
setuptools: 39.0.1
    Cython: None
```
</details>

#### Installation method
 - pip (via venv)

**Comment by snowman2** [comment]
`errcheck` isn't a parameter that is accepted in the constructor, but in the `__call__` method. The docs should be updated to reflect that. The current behavior is correct and errcheck used to be ignored.

**Comment by snowman2** [comment]
Also see #552
