### ISSUE TITLE
EPSG 32630 not working anymore

### ISSUE THREAD

**Issue by mraspaud** [pyproj4/pyproj#605]
#### Code Sample, a copy-pastable example if possible

```python
import pyproj                                                                                                                         
pyproj.__version__                                                                                                                    
# '2.6.0'

from pyproj import CRS                                                                                                                
CRS('epsg:32630')
```
```python-traceback
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/a001673/miniconda3/envs/py3/lib/python3.8/site-packages/pyproj/crs/crs.py", line 296, in __init__
    super().__init__(projstring)
  File "pyproj/_crs.pyx", line 2338, in pyproj._crs._CRS.__init__
pyproj.exceptions.CRSError: Invalid projection: epsg:32630: (Internal Proj Error: proj_create: cannot build projectedCRS 32630: cannot build geodeticCRS 4326: SQLite error on SELECT name, ellipsoid_auth_name, ellipsoid_code, prime_meridian_auth_name, prime_meridian_code, area_of_use_auth_name, area_of_use_code, publication_date, deprecated FROM geodetic_datum WHERE auth_name = ? AND code = ?: no such column: publication_date)
```

#### Problem description

A year or 2 ago, we were working with this projection and it was working fine (ftr: Sentinel 2 level 1c files).

However, there seems to be a problem with this projection now when creating a CRS with it.

#### Expected Output

A usable CRS object.

#### Environment Information
```
pyproj info:
    pyproj: 2.6.0
      PROJ: 6.3.1
  data dir: /home/a001673/miniconda3/envs/py3/lib/python3.8/site-packages/pyproj/proj_dir/share/proj

System:
    python: 3.8.2 | packaged by conda-forge | (default, Apr 24 2020, 08:20:52)  [GCC 7.3.0]
executable: /home/a001673/miniconda3/envs/py3/bin/python
   machine: Linux-4.18.0-147.5.1.el8_1.x86_64-x86_64-with-glibc2.10

Python deps:
       pip: 20.0.2
setuptools: 46.1.3.post20200325
    Cython: 0.29.14
```

#### Installation method
 - conda

#### Conda environment information (if you installed with conda):

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list | grep -E "proj|aenum"
proj                      6.3.1                hc80f0dc_1    conda-forge
pyproj                    2.6.0            py38h95a477d_0    conda-forge

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
     active environment : py3
    active env location : /home/a001673/miniconda3/envs/py3
            shell level : 2
       user config file : /home/a001673/.condarc
 populated config files : /home/a001673/.condarc
          conda version : 4.8.3
    conda-build version : not installed
         python version : 3.7.4.final.0
       virtual packages : __glibc=2.28
       base environment : /home/a001673/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/a001673/miniconda3/pkgs
                          /home/a001673/.conda/pkgs
       envs directories : /home/a001673/miniconda3/envs
                          /home/a001673/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.3 requests/2.23.0 CPython/3.7.4 Linux/4.18.0-147.5.1.el8_1.x86_64 rhel/8.1 glibc/2.28
                UID:GID : 62310:2000
             netrc file : None
           offline mode : False

```
</details>

**Comment by jorisvandenbossche** [comment]
For me this is working with the exact same versions:

```
In [1]: from pyproj import CRS                                                                                                                 
   ...: CRS('epsg:32630')    
Out[1]: 
<Projected CRS: EPSG:32630>
Name: WGS 84 / UTM zone 30N
Axis Info [cartesian]:
- E[east]: Easting (metre)
- N[north]: Northing (metre)
Area of Use:
- name: World - N hemisphere - 6°W to 0°W - by country
- bounds: (-6.0, 0.0, 0.0, 84.0)
Coordinate Operation:
- name: UTM zone 30N
- method: Transverse Mercator
Datum: World Geodetic System 1984
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich

```

so there should be going something wrong in your environment. 

From the output of `show_versions`, this is suspicious:

```
  data dir: /home/a001673/miniconda3/envs/py3/lib/python3.8/site-packages/pyproj/proj_dir/share/proj
```

it is taking the PROJ included in pyproj as the PROJ data path, while with conda, this should point to `envs/env-name/share/proj`. Did you also install pyproj as we wheel before? (it's strange in any case, as `conda list` is indicating it was installed from conda-forge.

**Comment by mraspaud** [comment]
Ok, hmmm, thanks, I'll try in a fresh environment.

**Comment by mraspaud** [comment]
Yes, my environment is messed up, works fine in a new one. Sorry for the noise.

**Comment by snowman2** [comment]
I have seen this come up a few times, might be worth mentioning in the `gotchas.rst`
