### ISSUE TITLE
Round-trip Albers fails with "point not within available datum shift grids"

### ISSUE THREAD

**Issue by allencnm** [pyproj4/pyproj#704]
#### Code Sample, a copy-pastable example if possible

```python
from pyproj import Transformer, CRS
from pyproj.enums import TransformDirection

lonlat = -74.9, 39.9
to_crs = CRS("esri:102003")
print(repr(to_crs))
tr = Transformer.from_crs("epsg:4326", to_crs, always_xy=True)
print(repr(tr))
albers_pt = tr.transform(*lonlat, errcheck=True)
print(f"Albers: {albers_pt}")
lonlat_rt = tr.transform(*albers_pt, errcheck=False, direction=TransformDirection.INVERSE)
print(f"Round trip: {lonlat} -> {lonlat_rt}")
lonlat_rt2 = tr.transform(*albers_pt, errcheck=True, direction=TransformDirection.INVERSE)
```
#### Problem description

When trying to do a round-trip from epsg:4326 to esri:102003 with errcheck=True, I get the following exception:
```
Traceback (most recent call last):
  File "gis_tst5.py", line 13, in <module>
    lonlat_rt2 = tr.transform(*albers_pt, errcheck=True, direction=TransformDirection.INVERSE)
  File "/opt/conda/lib/python3.8/site-packages/pyproj/transformer.py", line 430, in transform
    self._transformer._transform(
  File "pyproj/_transformer.pyx", line 487, in pyproj._transformer._Transformer._transform
pyproj.exceptions.ProjError: transform error: point not within available datum shift grids
```

The problem only occurs when using local proj-data or PROJ_NETWORK=ON. I also seem to get correct results when errcheck=False.
I'm guessing it's a PROJ problem, but I didn't know how to properly test it.

#### Expected Output

Something like the following, without throwing:
```
...
Round trip: (-74.9, 39.9) -> (-74.9, 39.900000000000006)
```

#### Environment Information
```
python -m pyproj -v
pyproj info:
    pyproj: 2.6.1.post1
      PROJ: 7.0.0
  data dir: /opt/conda/share/proj

System:
    python: 3.8.5 | packaged by conda-forge | (default, Jul 31 2020, 02:39:48)  [GCC 7.5.0]
executable: /opt/conda/bin/python
   machine: Linux-4.19.76-linuxkit-x86_64-with-glibc2.10

Python deps:
       pip: 20.2.2
setuptools: 49.6.0.post20200814
    Cython: 0.29.21
```

#### Installation method

conda

#### Conda environment information (if you installed with conda):

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list proj
# packages in environment at /opt/conda:
#
# Name                    Version                   Build  Channel
proj                      7.0.0                h966b41f_5    conda-forge
proj-data                 1.0                           1    conda-forge
pyproj                    2.6.1.post1      py38h7521cb9_0    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

     active environment : base
    active env location : /opt/conda
            shell level : 1
       user config file : /home/jovyan/.condarc
 populated config files : /opt/conda/.condarc
                          /home/jovyan/.condarc
          conda version : 4.8.3
    conda-build version : 3.20.0
         python version : 3.8.5.final.0
       virtual packages : __glibc=2.31
       base environment : /opt/conda  (writable)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /opt/conda/pkgs
                          /home/jovyan/.conda/pkgs
       envs directories : /opt/conda/envs
                          /home/jovyan/.conda/envs
               platform : linux-64
             user-agent : conda/4.8.3 requests/2.24.0 CPython/3.8.5 Linux/4.19.76-linuxkit ubuntu/20.04.1 glibc/2.31
                UID:GID : 1000:100
             netrc file : None
           offline mode : False
```
</details>

**Comment by snowman2** [comment]
I tried this out with PROJ 7.2 (not yet released) and pyproj 3 (not yet released) and enabled [PROJ debugging](https://pyproj4.github.io/pyproj/latest/advanced_examples.html#debugging-internal-proj):

```bash
PROJ_DEBUG=2 PROJ_NETWORK=ON python test_albers.py
```
Relevant output:
```
DEBUG:PROJ_DEBUG: Using coordinate operation Inverse of NAD83 to WGS 84 (57) + axis order change (2D) + USA_Contiguous_Albers_Equal_Area_Conic
DEBUG:PROJ_DEBUG: pj_open_lib(us_noaa_pahpgn.tif): call fopen(/home/snowal/.local/share/proj/us_noaa_pahpgn.tif) - failed
DEBUG:PROJ_DEBUG: pj_open_lib(pahpgn.gsb): call fopen(/home/snowal/.local/share/proj/pahpgn.gsb) - failed
DEBUG:PROJ_DEBUG: Using https://cdn.proj.org/us_noaa_pahpgn.tif
Albers: (1773370.9951035047, 466667.6736596611)
DEBUG:PROJ_DEBUG: Using coordinate operation Inverse of NAD83 to WGS 84 (31) + axis order change (2D) + USA_Contiguous_Albers_Equal_Area_Conic
DEBUG:PROJ_DEBUG: pj_open_lib(us_noaa_nyhpgn.tif): call fopen(/home/snowal/.local/share/proj/us_noaa_nyhpgn.tif) - failed
DEBUG:PROJ_DEBUG: pj_open_lib(nyhpgn.gsb): call fopen(/home/snowal/.local/share/proj/nyhpgn.gsb) - failed
DEBUG:PROJ_DEBUG: Using https://cdn.proj.org/us_noaa_nyhpgn.tif
DEBUG:PROJ_DEBUG: Did not result in valid result. Attempting a retry with another operation.
DEBUG:PROJ_DEBUG: Using coordinate operation Inverse of NAD83 to WGS 84 (57) + axis order change (2D) + USA_Contiguous_Albers_Equal_Area_Conic
Round trip: (-74.9, 39.9) -> (-74.9, 39.900000000000006)
```

From the output it seems like that the initial transform failed and it used the backup transformation. From what I can tell, the behavior of pyproj and PROJ is expected here.

**Comment by snowman2** [comment]
If I run with:
```
PROJ_DEBUG=2 python test_albers.py
```
Then no errors are raised because the best possible transformations was not attempted due to the missing grids:
```
DEBUG:PROJ_DEBUG: pj_open_lib(proj.ini): call fopen(/home/snowal/scripts/pyproj/pyproj/proj_dir/share/proj/proj.ini) - succeeded
DEBUG:PROJ_DEBUG: pj_open_lib(ca_nrc_NA83SCRS.tif): call fopen(/home/snowal/.local/share/proj/ca_nrc_NA83SCRS.tif) - failed
DEBUG:PROJ_DEBUG: pj_open_lib(NA83SCRS.GSB): call fopen(/home/snowal/.local/share/proj/NA83SCRS.GSB) - failed
DEBUG:PROJ_DEBUG: pj_open_lib(ca_nrc_ABCSRSV4.tif): call fopen(/home/snowal/.local/share/proj/ca_nrc_ABCSRSV4.tif) - failed
DEBUG:PROJ_DEBUG: pj_open_lib(ABCSRSV4.GSB): call fopen(/home/snowal/.local/share/proj/ABCSRSV4.GSB) - failed
DEBUG:PROJ_DEBUG: pj_open_lib(ca_nrc_SK83-98.tif): call fopen(/home/snowal/.local/share/proj/ca_nrc_SK83-98.tif) - failed
DEBUG:PROJ_DEBUG: pj_open_lib(SK83-98.GSB): call fopen(/home/snowal/.local/share/proj/SK83-98.GSB) - failed
DEBUG:PROJ_DEBUG: pj_open_lib(us_noaa_ethpgn.tif): call fopen(/home/snowal/.local/share/proj/us_noaa_ethpgn.tif) - failed
DEBUG:PROJ_DEBUG: pj_open_lib(ethpgn.gsb): call fopen(/home/snowal/.local/share/proj/ethpgn.gsb) - failed
DEBUG:PROJ_DEBUG: pj_open_lib(us_noaa_wthpgn.tif): call fopen(/home/snowal/.local/share/proj/us_noaa_wthpgn.tif) - failed
DEBUG:PROJ_DEBUG: pj_open_lib(wthpgn.gsb): call fopen(/home/snowal/.local/share/proj/wthpgn.gsb) - failed
DEBUG:PROJ_DEBUG: pj_open_lib(us_noaa_FL.tif): call fopen(/home/snowal/.local/share/proj/us_noaa_FL.tif) - failed
DEBUG:PROJ_DEBUG: pj_open_lib(FL): call fopen(/home/snowal/.local/share/proj/FL) - failed
DEBUG:PROJ_DEBUG: pj_open_lib(us_noaa_emhpgn.tif): call fopen(/home/snowal/.local/share/proj/us_noaa_emhpgn.tif) - failed
DEBUG:PROJ_DEBUG: pj_open_lib(emhpgn.gsb): call fopen(/home/snowal/.local/share/proj/emhpgn.gsb) - failed
DEBUG:PROJ_DEBUG: pj_open_lib(us_noaa_WO.tif): call fopen(/home/snowal/.local/share/proj/us_noaa_WO.tif) - failed
DEBUG:PROJ_DEBUG: pj_open_lib(WO): call fopen(/home/snowal/.local/share/proj/WO) - failed
DEBUG:PROJ_DEBUG: pj_open_lib(us_noaa_mihpgn.tif): call fopen(/home/snowal/.local/share/proj/us_noaa_mihpgn.tif) - failed
DEBUG:PROJ_DEBUG: pj_open_lib(mihpgn.gsb): call fopen(/home/snowal/.local/share/proj/mihpgn.gsb) - failed
DEBUG:PROJ_DEBUG: pj_open_lib(us_noaa_cnhpgn.tif): call fopen(/home/snowal/.local/share/proj/us_noaa_cnhpgn.tif) - failed
DEBUG:PROJ_DEBUG: pj_open_lib(cnhpgn.gsb): call fopen(/home/snowal/.local/share/proj/cnhpgn.gsb) - failed
DEBUG:PROJ_DEBUG: pj_open_lib(us_noaa_nvhpgn.tif): call fopen(/home/snowal/.local/share/proj/us_noaa_nvhpgn.tif) - failed
DEBUG:PROJ_DEBUG: pj_open_lib(nvhpgn.gsb): call fopen(/home/snowal/.local/share/proj/nvhpgn.gsb) - failed
DEBUG:PROJ_DEBUG: pj_open_lib(us_noaa_mnhpgn.tif): call fopen(/home/snowal/.local/share/proj/us_noaa_mnhpgn.tif) - failed
DEBUG:PROJ_DEBUG: pj_open_lib(mnhpgn.gsb): call fopen(/home/snowal/.local/share/proj/mnhpgn.gsb) - failed
DEBUG:PROJ_DEBUG: pj_open_lib(us_noaa_nmhpgn.tif): call fopen(/home/snowal/.local/share/proj/us_noaa_nmhpgn.tif) - failed
DEBUG:PROJ_DEBUG: pj_open_lib(nmhpgn.gsb): call fopen(/home/snowal/.local/share/proj/nmhpgn.gsb) - failed
DEBUG:PROJ_DEBUG: pj_open_lib(us_noaa_azhpgn.tif): call fopen(/home/snowal/.local/share/proj/us_noaa_azhpgn.tif) - failed
DEBUG:PROJ_DEBUG: pj_open_lib(azhpgn.gsb): call fopen(/home/snowal/.local/share/proj/azhpgn.gsb) - failed
DEBUG:PROJ_DEBUG: pj_open_lib(us_noaa_nyhpgn.tif): call fopen(/home/snowal/.local/share/proj/us_noaa_nyhpgn.tif) - failed
DEBUG:PROJ_DEBUG: pj_open_lib(nyhpgn.gsb): call fopen(/home/snowal/.local/share/proj/nyhpgn.gsb) - failed
DEBUG:PROJ_DEBUG: pj_open_lib(us_noaa_cshpgn.tif): call fopen(/home/snowal/.local/share/proj/us_noaa_cshpgn.tif) - failed
DEBUG:PROJ_DEBUG: pj_open_lib(cshpgn.gsb): call fopen(/home/snowal/.local/share/proj/cshpgn.gsb) - failed
DEBUG:PROJ_DEBUG: pj_open_lib(us_noaa_mohpgn.tif): call fopen(/home/snowal/.local/share/proj/us_noaa_mohpgn.tif) - failed
DEBUG:PROJ_DEBUG: pj_open_lib(mohpgn.gsb): call fopen(/home/snowal/.local/share/proj/mohpgn.gsb) - failed
DEBUG:PROJ_DEBUG: pj_open_lib(us_noaa_okhpgn.tif): call fopen(/home/snowal/.local/share/proj/us_noaa_okhpgn.tif) - failed
DEBUG:PROJ_DEBUG: pj_open_lib(okhpgn.gsb): call fopen(/home/snowal/.local/share/proj/okhpgn.gsb) - failed
DEBUG:PROJ_DEBUG: pj_open_lib(us_noaa_WI.tif): call fopen(/home/snowal/.local/share/proj/us_noaa_WI.tif) - failed
DEBUG:PROJ_DEBUG: pj_open_lib(WI): call fopen(/home/snowal/.local/share/proj/WI) - failed
DEBUG:PROJ_DEBUG: pj_open_lib(us_noaa_cohpgn.tif): call fopen(/home/snowal/.local/share/proj/us_noaa_cohpgn.tif) - failed
DEBUG:PROJ_DEBUG: pj_open_lib(cohpgn.gsb): call fopen(/home/snowal/.local/share/proj/cohpgn.gsb) - failed
DEBUG:PROJ_DEBUG: pj_open_lib(us_noaa_wmhpgn.tif): call fopen(/home/snowal/.local/share/proj/us_noaa_wmhpgn.tif) - failed
DEBUG:PROJ_DEBUG: pj_open_lib(wmhpgn.gsb): call fopen(/home/snowal/.local/share/proj/wmhpgn.gsb) - failed
DEBUG:PROJ_DEBUG: pj_open_lib(us_noaa_wyhpgn.tif): call fopen(/home/snowal/.local/share/proj/us_noaa_wyhpgn.tif) - failed
DEBUG:PROJ_DEBUG: pj_open_lib(wyhpgn.gsb): call fopen(/home/snowal/.local/share/proj/wyhpgn.gsb) - failed
DEBUG:PROJ_DEBUG: pj_open_lib(us_noaa_nchpgn.tif): call fopen(/home/snowal/.local/share/proj/us_noaa_nchpgn.tif) - failed
DEBUG:PROJ_DEBUG: pj_open_lib(nchpgn.gsb): call fopen(/home/snowal/.local/share/proj/nchpgn.gsb) - failed
DEBUG:PROJ_DEBUG: pj_open_lib(us_noaa_nbhpgn.tif): call fopen(/home/snowal/.local/share/proj/us_noaa_nbhpgn.tif) - failed
DEBUG:PROJ_DEBUG: pj_open_lib(nbhpgn.gsb): call fopen(/home/snowal/.local/share/proj/nbhpgn.gsb) - failed
DEBUG:PROJ_DEBUG: pj_open_lib(us_noaa_uthpgn.tif): call fopen(/home/snowal/.local/share/proj/us_noaa_uthpgn.tif) - failed
DEBUG:PROJ_DEBUG: pj_open_lib(uthpgn.gsb): call fopen(/home/snowal/.local/share/proj/uthpgn.gsb) - failed
DEBUG:PROJ_DEBUG: pj_open_lib(us_noaa_vahpgn.tif): call fopen(/home/snowal/.local/share/proj/us_noaa_vahpgn.tif) - failed
DEBUG:PROJ_DEBUG: pj_open_lib(vahpgn.gsb): call fopen(/home/snowal/.local/share/proj/vahpgn.gsb) - failed
DEBUG:PROJ_DEBUG: pj_open_lib(us_noaa_ilhpgn.tif): call fopen(/home/snowal/.local/share/proj/us_noaa_ilhpgn.tif) - failed
DEBUG:PROJ_DEBUG: pj_open_lib(ilhpgn.gsb): call fopen(/home/snowal/.local/share/proj/ilhpgn.gsb) - failed
DEBUG:PROJ_DEBUG: pj_open_lib(us_noaa_sdhpgn.tif): call fopen(/home/snowal/.local/share/proj/us_noaa_sdhpgn.tif) - failed
DEBUG:PROJ_DEBUG: pj_open_lib(sdhpgn.gsb): call fopen(/home/snowal/.local/share/proj/sdhpgn.gsb) - failed
DEBUG:PROJ_DEBUG: pj_open_lib(us_noaa_lahpgn.tif): call fopen(/home/snowal/.local/share/proj/us_noaa_lahpgn.tif) - failed
DEBUG:PROJ_DEBUG: pj_open_lib(lahpgn.gsb): call fopen(/home/snowal/.local/share/proj/lahpgn.gsb) - failed
DEBUG:PROJ_DEBUG: pj_open_lib(us_noaa_gahpgn.tif): call fopen(/home/snowal/.local/share/proj/us_noaa_gahpgn.tif) - failed
DEBUG:PROJ_DEBUG: pj_open_lib(gahpgn.gsb): call fopen(/home/snowal/.local/share/proj/gahpgn.gsb) - failed
DEBUG:PROJ_DEBUG: pj_open_lib(us_noaa_kshpgn.tif): call fopen(/home/snowal/.local/share/proj/us_noaa_kshpgn.tif) - failed
DEBUG:PROJ_DEBUG: pj_open_lib(kshpgn.gsb): call fopen(/home/snowal/.local/share/proj/kshpgn.gsb) - failed
DEBUG:PROJ_DEBUG: pj_open_lib(us_noaa_kyhpgn.tif): call fopen(/home/snowal/.local/share/proj/us_noaa_kyhpgn.tif) - failed
DEBUG:PROJ_DEBUG: pj_open_lib(kyhpgn.gsb): call fopen(/home/snowal/.local/share/proj/kyhpgn.gsb) - failed
DEBUG:PROJ_DEBUG: pj_open_lib(us_noaa_ndhpgn.tif): call fopen(/home/snowal/.local/share/proj/us_noaa_ndhpgn.tif) - failed
DEBUG:PROJ_DEBUG: pj_open_lib(ndhpgn.gsb): call fopen(/home/snowal/.local/share/proj/ndhpgn.gsb) - failed
DEBUG:PROJ_DEBUG: pj_open_lib(us_noaa_iahpgn.tif): call fopen(/home/snowal/.local/share/proj/us_noaa_iahpgn.tif) - failed
DEBUG:PROJ_DEBUG: pj_open_lib(iahpgn.gsb): call fopen(/home/snowal/.local/share/proj/iahpgn.gsb) - failed
DEBUG:PROJ_DEBUG: pj_open_lib(us_noaa_mshpgn.tif): call fopen(/home/snowal/.local/share/proj/us_noaa_mshpgn.tif) - failed
DEBUG:PROJ_DEBUG: pj_open_lib(mshpgn.gsb): call fopen(/home/snowal/.local/share/proj/mshpgn.gsb) - failed
DEBUG:PROJ_DEBUG: pj_open_lib(us_noaa_alhpgn.tif): call fopen(/home/snowal/.local/share/proj/us_noaa_alhpgn.tif) - failed
DEBUG:PROJ_DEBUG: pj_open_lib(alhpgn.gsb): call fopen(/home/snowal/.local/share/proj/alhpgn.gsb) - failed
DEBUG:PROJ_DEBUG: pj_open_lib(us_noaa_arhpgn.tif): call fopen(/home/snowal/.local/share/proj/us_noaa_arhpgn.tif) - failed
DEBUG:PROJ_DEBUG: pj_open_lib(arhpgn.gsb): call fopen(/home/snowal/.local/share/proj/arhpgn.gsb) - failed
DEBUG:PROJ_DEBUG: pj_open_lib(us_noaa_wvhpgn.tif): call fopen(/home/snowal/.local/share/proj/us_noaa_wvhpgn.tif) - failed
DEBUG:PROJ_DEBUG: pj_open_lib(wvhpgn.gsb): call fopen(/home/snowal/.local/share/proj/wvhpgn.gsb) - failed
DEBUG:PROJ_DEBUG: pj_open_lib(us_noaa_mehpgn.tif): call fopen(/home/snowal/.local/share/proj/us_noaa_mehpgn.tif) - failed
DEBUG:PROJ_DEBUG: pj_open_lib(mehpgn.gsb): call fopen(/home/snowal/.local/share/proj/mehpgn.gsb) - failed
DEBUG:PROJ_DEBUG: pj_open_lib(us_noaa_ohhpgn.tif): call fopen(/home/snowal/.local/share/proj/us_noaa_ohhpgn.tif) - failed
DEBUG:PROJ_DEBUG: pj_open_lib(ohhpgn.gsb): call fopen(/home/snowal/.local/share/proj/ohhpgn.gsb) - failed
DEBUG:PROJ_DEBUG: pj_open_lib(us_noaa_schpgn.tif): call fopen(/home/snowal/.local/share/proj/us_noaa_schpgn.tif) - failed
DEBUG:PROJ_DEBUG: pj_open_lib(schpgn.gsb): call fopen(/home/snowal/.local/share/proj/schpgn.gsb) - failed
DEBUG:PROJ_DEBUG: pj_open_lib(us_noaa_pahpgn.tif): call fopen(/home/snowal/.local/share/proj/us_noaa_pahpgn.tif) - failed
DEBUG:PROJ_DEBUG: pj_open_lib(pahpgn.gsb): call fopen(/home/snowal/.local/share/proj/pahpgn.gsb) - failed
DEBUG:PROJ_DEBUG: pj_open_lib(us_noaa_nehpgn.tif): call fopen(/home/snowal/.local/share/proj/us_noaa_nehpgn.tif) - failed
DEBUG:PROJ_DEBUG: pj_open_lib(nehpgn.gsb): call fopen(/home/snowal/.local/share/proj/nehpgn.gsb) - failed
DEBUG:PROJ_DEBUG: pj_open_lib(us_noaa_TN.tif): call fopen(/home/snowal/.local/share/proj/us_noaa_TN.tif) - failed
DEBUG:PROJ_DEBUG: pj_open_lib(TN): call fopen(/home/snowal/.local/share/proj/TN) - failed
DEBUG:PROJ_DEBUG: pj_open_lib(us_noaa_inhpgn.tif): call fopen(/home/snowal/.local/share/proj/us_noaa_inhpgn.tif) - failed
DEBUG:PROJ_DEBUG: pj_open_lib(inhpgn.gsb): call fopen(/home/snowal/.local/share/proj/inhpgn.gsb) - failed
DEBUG:PROJ_DEBUG: pj_open_lib(us_noaa_MD.tif): call fopen(/home/snowal/.local/share/proj/us_noaa_MD.tif) - failed
DEBUG:PROJ_DEBUG: pj_open_lib(MD): call fopen(/home/snowal/.local/share/proj/MD) - failed
DEBUG:PROJ_DEBUG: pj_open_lib(us_noaa_njhpgn.tif): call fopen(/home/snowal/.local/share/proj/us_noaa_njhpgn.tif) - failed
DEBUG:PROJ_DEBUG: pj_open_lib(njhpgn.gsb): call fopen(/home/snowal/.local/share/proj/njhpgn.gsb) - failed
<Concatenated Operation Transformer: pipeline>
Description: axis order change (2D) + Inverse of NAD83 to WGS 84 (1) + axis order change (2D) + USA_Contiguous_Albers_Equal_Area_Conic
Area of Use:
- name: North America - Canada and USA (CONUS, Alaska mainland)
- bounds: (-172.54, 23.81, -47.74, 86.46)
Albers: (1773370.9846869048, 466667.8457989395)
Round trip: (-74.9, 39.9) -> (-74.9, 39.9)

```

**Comment by snowman2** [comment]
Hmmm, it seems that on the inverse transformation, it selects the one used on the forward transformation after the initial failure. So, an error probably shouldn't be raised. Will need to dig into this a bit and see what is going on.

**Comment by snowman2** [comment]
Resolved upstream.

**Comment by allencnm** [comment]
Thanks for helping to have this resolved so quickly! :-)
