### ISSUE TITLE
Release 3.0.1

### ISSUE THREAD

**Issue by snowman2** [pyproj4/pyproj#785]
https://github.com/pyproj4/pyproj/releases/tag/3.0.1rc0

The plan is to release with PROJ 7.2.1 in the wheels since this is a patch release.

Release Candidate 0 Status:
- [x] Linux/OSX wheels (https://github.com/pyproj4/pyproj-wheels/pull/33)
- [ ] Windows wheels (ping @cgohlke)
- [x] Conda Forge (https://github.com/conda-forge/pyproj-feedstock/pull/85)
- [x] Debian (ping @sebastic)

Plan to release when testing is completed or Friday, March 5th. Testing is always appreciated, but definitely not required.

**Comment by sebastic** [comment]
3.0.1rc0 like 3.0.0 fails to build the man pages as reported in [Debian Bug #982698](https://bugs.debian.org/982698):
```
PYTHONPATH=/build/python-pyproj/.pybuild/cpython3_3.9_pyproj/build make -C /build/python-pyproj/docs man
make[2]: Entering directory '/build/python-pyproj/docs'
Running Sphinx v3.4.3
making output directory... done
building [mo]: targets for 0 po files that are out of date
building [man]: all manpages
updating environment: [new config] 33 added, 0 changed, 0 removed
reading sources... [  3%] advanced_examples
reading sources... [  6%] api/aoi
reading sources... [  9%] api/crs/coordinate_operation
reading sources... [ 12%] api/crs/coordinate_system
reading sources... [ 15%] api/crs/crs
reading sources... [ 18%] api/crs/datum
reading sources... [ 21%] api/crs/enums
reading sources... [ 24%] api/crs/index
reading sources... [ 27%] api/database
reading sources... [ 30%] api/datadir
reading sources... [ 33%] api/enums
reading sources... [ 36%] api/exceptions
reading sources... [ 39%] api/geod
reading sources... [ 42%] api/global_context
reading sources... [ 45%] api/index
reading sources... [ 48%] api/list
reading sources... [ 51%] api/network
reading sources... [ 54%] api/proj
reading sources... [ 57%] api/show_versions
reading sources... [ 60%] api/sync
reading sources... [ 63%] api/transformer
reading sources... [ 66%] build_crs
reading sources... [ 69%] build_crs_cf
reading sources... [ 72%] cli

Exception occurred:
  File "/usr/lib/python3/dist-packages/sphinxarg/parser.py", line 40, in _try_add_parser_attribute
    data[attribname] = attribval % {'prog': data['prog']}
KeyError: 'prog'
The full traceback has been saved in /tmp/sphinx-err-c2bpk2op.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```
```
# Sphinx version: 3.4.3
# Python version: 3.9.2 (CPython)
# Docutils version: 0.16 release
# Jinja2 version: 2.11.3
# Last messages:
#   reading sources... [ 45%] api/index
#   reading sources... [ 48%] api/list
#   reading sources... [ 51%] api/network
#   reading sources... [ 54%] api/proj
#   reading sources... [ 57%] api/show_versions
#   reading sources... [ 60%] api/sync
#   reading sources... [ 63%] api/transformer
#   reading sources... [ 66%] build_crs
#   reading sources... [ 69%] build_crs_cf
#   reading sources... [ 72%] cli
# Loaded extensions:
#   sphinx.ext.mathjax (3.4.3) from /usr/lib/python3/dist-packages/sphinx/ext/mathjax.py
#   alabaster (0.7.8) from /usr/lib/python3/dist-packages/alabaster/__init__.py
#   sphinx.ext.autodoc.type_comment (3.4.3) from /usr/lib/python3/dist-packages/sphinx/ext/autodoc/type_comment.py
#   sphinx.ext.autodoc (3.4.3) from /usr/lib/python3/dist-packages/sphinx/ext/autodoc/__init__.py
#   sphinx.ext.viewcode (3.4.3) from /usr/lib/python3/dist-packages/sphinx/ext/viewcode.py
#   sphinx.ext.napoleon (3.4.3) from /usr/lib/python3/dist-packages/sphinx/ext/napoleon/__init__.py
#   sphinx.ext.intersphinx (3.4.3) from /usr/lib/python3/dist-packages/sphinx/ext/intersphinx.py
#   sphinxarg.ext (unknown version) from /usr/lib/python3/dist-packages/sphinxarg/ext.py
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sphinx/cmd/build.py", line 280, in build_main
    app.build(args.force_all, filenames)
  File "/usr/lib/python3/dist-packages/sphinx/application.py", line 346, in build
    self.builder.build_update()
  File "/usr/lib/python3/dist-packages/sphinx/builders/__init__.py", line 293, in build_update
    self.build(['__all__'], to_build)
  File "/usr/lib/python3/dist-packages/sphinx/builders/__init__.py", line 310, in build
    updated_docnames = set(self.read())
  File "/usr/lib/python3/dist-packages/sphinx/builders/__init__.py", line 417, in read
    self._read_serial(docnames)
  File "/usr/lib/python3/dist-packages/sphinx/builders/__init__.py", line 438, in _read_serial
    self.read_doc(docname)
  File "/usr/lib/python3/dist-packages/sphinx/builders/__init__.py", line 478, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "/usr/lib/python3/dist-packages/sphinx/io.py", line 221, in read_doc
    pub.publish()
  File "/usr/lib/python3/dist-packages/docutils/core.py", line 217, in publish
    self.document = self.reader.read(self.source, self.parser,
  File "/usr/lib/python3/dist-packages/sphinx/io.py", line 126, in read
    self.parse()
  File "/usr/lib/python3/dist-packages/docutils/readers/__init__.py", line 77, in parse
    self.parser.parse(self.input, document)
  File "/usr/lib/python3/dist-packages/sphinx/parsers.py", line 104, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py", line 171, in run
    results = StateMachineWS.run(self, input_lines, input_offset,
  File "/usr/lib/python3/dist-packages/docutils/statemachine.py", line 241, in run
    context, next_state, result = self.check_line(
  File "/usr/lib/python3/dist-packages/docutils/statemachine.py", line 459, in check_line
    return method(match, context, next_state)
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py", line 2770, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py", line 328, in section
    self.new_subsection(title, lineno, messages)
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py", line 394, in new_subsection
    newabsoffset = self.nested_parse(
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py", line 197, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/lib/python3/dist-packages/docutils/statemachine.py", line 241, in run
    context, next_state, result = self.check_line(
  File "/usr/lib/python3/dist-packages/docutils/statemachine.py", line 459, in check_line
    return method(match, context, next_state)
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py", line 2343, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py", line 2355, in explicit_construct
    return method(self, expmatch)
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py", line 2097, in directive
    return self.run_directive(
  File "/usr/lib/python3/dist-packages/docutils/parsers/rst/states.py", line 2147, in run_directive
    result = directive_instance.run()
  File "/usr/lib/python3/dist-packages/sphinxarg/ext.py", line 467, in run
    result = parse_parser(
  File "/usr/lib/python3/dist-packages/sphinxarg/parser.py", line 95, in parse_parser
    parse_parser(subaction, subdata, **kwargs)
  File "/usr/lib/python3/dist-packages/sphinxarg/parser.py", line 62, in parse_parser
    _try_add_parser_attribute(data, parser, 'description')
  File "/usr/lib/python3/dist-packages/sphinxarg/parser.py", line 40, in _try_add_parser_attribute
    data[attribname] = attribval % {'prog': data['prog']}
KeyError: 'prog'
```

The build, test, and install targets work fine with PROJ 8.0.0 when the manpage is not built.

**Comment by snowman2** [comment]
@sebastic I cannot reproduce your issue: https://github.com/pyproj4/pyproj/pull/786

**Comment by sebastic** [comment]
I can reproduce it with the same steps as CI too:
```
# python3 setup.py develop
running develop
running egg_info
creating pyproj.egg-info
writing pyproj.egg-info/PKG-INFO
writing dependency_links to pyproj.egg-info/dependency_links.txt
writing entry points to pyproj.egg-info/entry_points.txt
writing requirements to pyproj.egg-info/requires.txt
writing top-level names to pyproj.egg-info/top_level.txt
writing manifest file 'pyproj.egg-info/SOURCES.txt'
reading manifest file 'pyproj.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'pyproj/*.pyd'
no previously-included directories found matching 'pyproj/proj_dir'
writing manifest file 'pyproj.egg-info/SOURCES.txt'
running build_ext
building 'pyproj._geod' extension
x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -ffile-prefix-map=/build/python3.9-RNBry6/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -ffile-prefix-map=/build/python3.9-RNBry6/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include -I/usr/include/python3.9 -c pyproj/_geod.c -o build/temp.linux-x86_64-3.9/pyproj/_geod.o
creating build/lib.linux-x86_64-3.9
creating build/lib.linux-x86_64-3.9/pyproj
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fwrapv -O2 -Wl,-z,relro -g -fwrapv -O2 -g -ffile-prefix-map=/build/python3.9-RNBry6/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.9/pyproj/_geod.o -lproj -o build/lib.linux-x86_64-3.9/pyproj/_geod.cpython-39-x86_64-linux-gnu.so
building 'pyproj._crs' extension
x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -ffile-prefix-map=/build/python3.9-RNBry6/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -ffile-prefix-map=/build/python3.9-RNBry6/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include -I/usr/include/python3.9 -c pyproj/_crs.c -o build/temp.linux-x86_64-3.9/pyproj/_crs.o
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fwrapv -O2 -Wl,-z,relro -g -fwrapv -O2 -g -ffile-prefix-map=/build/python3.9-RNBry6/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.9/pyproj/_crs.o -lproj -o build/lib.linux-x86_64-3.9/pyproj/_crs.cpython-39-x86_64-linux-gnu.so
building 'pyproj._transformer' extension
x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -ffile-prefix-map=/build/python3.9-RNBry6/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -ffile-prefix-map=/build/python3.9-RNBry6/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include -I/usr/include/python3.9 -c pyproj/_transformer.c -o build/temp.linux-x86_64-3.9/pyproj/_transformer.o
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fwrapv -O2 -Wl,-z,relro -g -fwrapv -O2 -g -ffile-prefix-map=/build/python3.9-RNBry6/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.9/pyproj/_transformer.o -lproj -o build/lib.linux-x86_64-3.9/pyproj/_transformer.cpython-39-x86_64-linux-gnu.so
building 'pyproj._compat' extension
x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -ffile-prefix-map=/build/python3.9-RNBry6/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -ffile-prefix-map=/build/python3.9-RNBry6/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include -I/usr/include/python3.9 -c pyproj/_compat.c -o build/temp.linux-x86_64-3.9/pyproj/_compat.o
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fwrapv -O2 -Wl,-z,relro -g -fwrapv -O2 -g -ffile-prefix-map=/build/python3.9-RNBry6/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.9/pyproj/_compat.o -lproj -o build/lib.linux-x86_64-3.9/pyproj/_compat.cpython-39-x86_64-linux-gnu.so
building 'pyproj.database' extension
x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -ffile-prefix-map=/build/python3.9-RNBry6/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -ffile-prefix-map=/build/python3.9-RNBry6/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include -I/usr/include/python3.9 -c pyproj/database.c -o build/temp.linux-x86_64-3.9/pyproj/database.o
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fwrapv -O2 -Wl,-z,relro -g -fwrapv -O2 -g -ffile-prefix-map=/build/python3.9-RNBry6/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.9/pyproj/database.o -lproj -o build/lib.linux-x86_64-3.9/pyproj/database.cpython-39-x86_64-linux-gnu.so
building 'pyproj._datadir' extension
x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -ffile-prefix-map=/build/python3.9-RNBry6/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -ffile-prefix-map=/build/python3.9-RNBry6/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include -I/usr/include/python3.9 -c pyproj/_datadir.c -o build/temp.linux-x86_64-3.9/pyproj/_datadir.o
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fwrapv -O2 -Wl,-z,relro -g -fwrapv -O2 -g -ffile-prefix-map=/build/python3.9-RNBry6/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.9/pyproj/_datadir.o -lproj -o build/lib.linux-x86_64-3.9/pyproj/_datadir.cpython-39-x86_64-linux-gnu.so
building 'pyproj.list' extension
x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -ffile-prefix-map=/build/python3.9-RNBry6/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -ffile-prefix-map=/build/python3.9-RNBry6/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include -I/usr/include/python3.9 -c pyproj/list.c -o build/temp.linux-x86_64-3.9/pyproj/list.o
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fwrapv -O2 -Wl,-z,relro -g -fwrapv -O2 -g -ffile-prefix-map=/build/python3.9-RNBry6/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.9/pyproj/list.o -lproj -o build/lib.linux-x86_64-3.9/pyproj/list.cpython-39-x86_64-linux-gnu.so
building 'pyproj._network' extension
x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -ffile-prefix-map=/build/python3.9-RNBry6/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -ffile-prefix-map=/build/python3.9-RNBry6/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include -I/usr/include/python3.9 -c pyproj/_network.c -o build/temp.linux-x86_64-3.9/pyproj/_network.o
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fwrapv -O2 -Wl,-z,relro -g -fwrapv -O2 -g -ffile-prefix-map=/build/python3.9-RNBry6/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.9/pyproj/_network.o -lproj -o build/lib.linux-x86_64-3.9/pyproj/_network.cpython-39-x86_64-linux-gnu.so
building 'pyproj._sync' extension
x86_64-linux-gnu-gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -ffile-prefix-map=/build/python3.9-RNBry6/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -g -ffile-prefix-map=/build/python3.9-RNBry6/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/usr/include -I/usr/include/python3.9 -c pyproj/_sync.c -o build/temp.linux-x86_64-3.9/pyproj/_sync.o
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -g -fwrapv -O2 -Wl,-z,relro -g -fwrapv -O2 -g -ffile-prefix-map=/build/python3.9-RNBry6/python3.9-3.9.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-x86_64-3.9/pyproj/_sync.o -lproj -o build/lib.linux-x86_64-3.9/pyproj/_sync.cpython-39-x86_64-linux-gnu.so
copying build/lib.linux-x86_64-3.9/pyproj/_geod.cpython-39-x86_64-linux-gnu.so -> pyproj
copying build/lib.linux-x86_64-3.9/pyproj/_crs.cpython-39-x86_64-linux-gnu.so -> pyproj
copying build/lib.linux-x86_64-3.9/pyproj/_transformer.cpython-39-x86_64-linux-gnu.so -> pyproj
copying build/lib.linux-x86_64-3.9/pyproj/_compat.cpython-39-x86_64-linux-gnu.so -> pyproj
copying build/lib.linux-x86_64-3.9/pyproj/database.cpython-39-x86_64-linux-gnu.so -> pyproj
copying build/lib.linux-x86_64-3.9/pyproj/_datadir.cpython-39-x86_64-linux-gnu.so -> pyproj
copying build/lib.linux-x86_64-3.9/pyproj/list.cpython-39-x86_64-linux-gnu.so -> pyproj
copying build/lib.linux-x86_64-3.9/pyproj/_network.cpython-39-x86_64-linux-gnu.so -> pyproj
copying build/lib.linux-x86_64-3.9/pyproj/_sync.cpython-39-x86_64-linux-gnu.so -> pyproj
Creating /usr/local/lib/python3.9/dist-packages/pyproj.egg-link (link to .)
Adding pyproj 3.0.1rc0 to easy-install.pth file
Installing pyproj script to /usr/local/bin

Installed /build/python-pyproj
Processing dependencies for pyproj==3.0.1rc0
Searching for certifi==2020.6.20
Best match: certifi 2020.6.20
Adding certifi 2020.6.20 to easy-install.pth file

Using /usr/lib/python3/dist-packages
Finished processing dependencies for pyproj==3.0.1rc0
# make -C docs/ man
make: Entering directory '/build/python-pyproj/docs'
Running Sphinx v3.4.3
building [mo]: targets for 0 po files that are out of date
building [man]: all manpages
updating environment: [new config] 33 added, 0 changed, 0 removed
reading sources... [ 72%] cli                                                                                                                                                                                                               
Exception occurred:
  File "/usr/lib/python3/dist-packages/sphinxarg/parser.py", line 40, in _try_add_parser_attribute
    data[attribname] = attribval % {'prog': data['prog']}
KeyError: 'prog'
The full traceback has been saved in /tmp/sphinx-err-77jf52xc.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [Makefile:20: man] Error 2
make: Leaving directory '/build/python-pyproj/docs'
```

Debian unstable has the same versions of sphinx & sphinx-argparse as the CI, so a likely cause is patches included in the Debian package, this change specifically is suspicious:
```diff
--- sphinx-argparse.orig/sphinxarg/parser.py
+++ sphinx-argparse/sphinxarg/parser.py
@@ -37,7 +37,7 @@
     if not isinstance(attribval, str):
         return
     if len(attribval) > 0:
-        data[attribname] = attribval
+        data[attribname] = attribval % {'prog': data['prog']}
 
 
 def _format_usage_without_prefix(parser):
```
https://sources.debian.org/src/sphinx-argparse/0.2.5-1/debian/patches/pytest_prog_name_varies.patch/#L113

**Comment by snowman2** [comment]
Fix: https://github.com/alex-rudakov/sphinx-argparse/pull/113#pullrequestreview-602011250

**Comment by snowman2** [comment]
Thanks @sebastic for testing :+1:
