### ISSUE TITLE
CRSError is raised when other package is imported first

### ISSUE THREAD

**Issue by martin-majlis** [pyproj4/pyproj#801]
#### Code Sample, a copy-pastable example if possible

Install dependencies: `pip install -U probstructs==0.2.6 pyproj==3.0.0.post1`

```python
from probstructs import ExponentialCountMinSketch
from pyproj import CRS

print(repr(CRS("ESRI:54009")))

ec = ExponentialCountMinSketch(10, 10, 10)
ec.inc("A", 1, 1)
print(ec.get("A", 1, 1))
```
#### Problem description

When code fromabove is executed it fails with following error:

```
Traceback (most recent call last):
  File "crs_init.py", line 4, in <module>
    print(repr(CRS("ESRI:54009")))
  File "/usr/local/lib/python3.8/site-packages/pyproj/crs/crs.py", line 296, in __init__
    super().__init__(projstring)
  File "pyproj/_crs.pyx", line 2302, in pyproj._crs._CRS.__init__
pyproj.exceptions.CRSError: Invalid projection: ESRI:54009: (Internal Proj Error: proj_create: cannot build projectedCRS 54009: buildUnit: non double value)
```

#### Expected Output

When imports are swapped:

```python
from pyproj import CRS
from probstructs import ExponentialCountMinSketch

print(repr(CRS("ESRI:54009")))

ec = ExponentialCountMinSketch(10, 10, 10)
ec.inc("A", 1, 1)
print(ec.get("A", 1, 1))
```

Then expected output is produced:

```
<Projected CRS: ESRI:54009>
Name: World_Mollweide
Axis Info [cartesian]:
- E[east]: Easting (metre)
- N[north]: Northing (metre)
Area of Use:
- name: World.
- bounds: (-180.0, -90.0, 180.0, 90.0)
Coordinate Operation:
- name: World_Mollweide
- method: Mollweide
Datum: World Geodetic System 1984
- Ellipsoid: WGS 84
- Prime Meridian: Greenwich

1
```

#### Minimal Example In Docker

Minimal example could be also run in docker. Please, extract the following archive and run ` ./docker-run.sh`.

[pyproj-crs.tar.gz](https://github.com/pyproj4/pyproj/files/6141912/pyproj-crs.tar.gz)

#### Environment Information

 - Output from: `pyproj -v`
 ```
pyproj info:
    pyproj: 3.0.0.post1
      PROJ: 7.2.0
  data dir: /home/martin/.conda/envs/bd-web/lib/python3.8/site-packages/pyproj/proj_dir/share/proj
user_data_dir: /home/martin/.local/share/proj

System:
    python: 3.8.5 | packaged by conda-forge | (default, Sep 16 2020, 18:01:20)  [GCC 7.5.0]
executable: /home/martin/.conda/envs/bd-web/bin/python
   machine: Linux-5.4.72-microsoft-standard-WSL2-x86_64-with-glibc2.10

Python deps:
/home/martin/.local/lib/python3.8/site-packages/_distutils_hack/__init__.py:30: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
       pip: 21.0.1
setuptools: 50.0.0
    Cython: None
```

 - Output from: `python -m pyproj -v`
```
pyproj info:
    pyproj: 3.0.0.post1
      PROJ: 7.2.0
  data dir: /home/martin/.conda/envs/bd-web/lib/python3.8/site-packages/pyproj/proj_dir/share/proj
user_data_dir: /home/martin/.local/share/proj

System:
    python: 3.8.5 | packaged by conda-forge | (default, Sep 16 2020, 18:01:20)  [GCC 7.5.0]
executable: /home/martin/.conda/envs/bd-web/bin/python
   machine: Linux-5.4.72-microsoft-standard-WSL2-x86_64-with-glibc2.10

Python deps:
/home/martin/.local/lib/python3.8/site-packages/_distutils_hack/__init__.py:30: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
       pip: 21.0.1
setuptools: 50.0.0
    Cython: None
```

 - Python version (`python -c "import sys; print(sys.version.replace('\n', ' '))"`)
 
```
3.8.5 | packaged by conda-forge | (default, Sep 16 2020, 18:01:20)  [GCC 7.5.0]
```

 - Operation System Information (`python -c "import platform; print(platform.platform())"`) 
 - 
```
Linux-5.4.72-microsoft-standard-WSL2-x86_64-with-glibc2.10
```

#### Installation method
 - conda

#### Conda environment information (if you installed with conda):

<br/>

Environment (<code>conda list</code>):
<details>

```
$ conda list proj

conda list proj
# packages in environment at /home/martin/.conda/envs/bd-web:
#
# Name                    Version                   Build  Channel
proj                      7.1.0                h966b41f_1    conda-forge
pyproj                    3.0.0.post1              pypi_0    pypi

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
     active environment : bd-web
    active env location : /home/martin/.conda/envs/bd-web
            shell level : 2
       user config file : /home/martin/.condarc
 populated config files :
          conda version : 4.8.3
    conda-build version : not installed
         python version : 3.8.3.final.0
       virtual packages : __glibc=2.23
       base environment : /home/martin/miniconda3  (read only)
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /home/martin/miniconda3/pkgs
                          /home/martin/.conda/pkgs
       envs directories : /home/martin/.conda/envs
                          /home/martin/miniconda3/envs
               platform : linux-64
             user-agent : conda/4.8.3 requests/2.23.0 CPython/3.8.3 Linux/5.4.72-microsoft-standard-WSL2 ubuntu/16.04.3 glibc/2.23
                UID:GID : 1000:1000
             netrc file : None
           offline mode : False

```
</details>

**Comment by snowman2** [comment]
@martin-majlis it appears that you are mixing pypi and conda packages. I would recommend creating a new conda environment and `conda install -c conda-forge pyproj`.

**Comment by martin-majlis** [comment]
@snowman2 : Thanks, but it does not look to be based on the mixing stuff.

```
mkdir -p /tmp/pyproj-exp
cd /tmp/pyproj-exp
python3 -m venv venv
source ./venv/bin/activate
pip install -U probstructs==0.2.6 pyproj==3.0.0.post1
python -c 'from probstructs import ExponentialCountMinSketch; from pyproj import CRS; print(repr(CRS("ESRI:54009")))'
```

Ends up with the same error:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/pyproj-exp/venv/lib/python3.8/site-packages/pyproj/crs/crs.py", line 296, in __init__
    super().__init__(projstring)
  File "pyproj/_crs.pyx", line 2302, in pyproj._crs._CRS.__init__
pyproj.exceptions.CRSError: Invalid projection: ESRI:54009: (Internal Proj Error: proj_create: cannot build projectedCRS 54009: buildUnit: non double value)
```

Result of `pyproj -v`

```
pyproj info:
    pyproj: 3.0.0.post1
      PROJ: 7.2.0
  data dir: /tmp/pyproj-exp/venv/lib/python3.8/site-packages/pyproj/proj_dir/share/proj
user_data_dir: /home/martin/.local/share/proj

System:
    python: 3.8.7 (default, Dec 21 2020, 20:10:35)  [GCC 7.5.0]
executable: /tmp/pyproj-exp/venv/bin/python3
   machine: Linux-5.4.0-66-generic-x86_64-with-glibc2.27

Python deps:
/tmp/pyproj-exp/venv/lib/python3.8/site-packages/setuptools/distutils_patch.py:25: UserWarning: Distutils was imported before Setuptools. This usage is discouraged and may exhibit undesirable behaviors or errors. Please use Setuptools' objects directly or at least import Setuptools first.
  warnings.warn(
       pip: 20.2.3
setuptools: 49.2.1
    Cython: None
```
Furthermore even the dockerized example is failing with the same error.

**Comment by snowman2** [comment]
I am at a loss for what the issue could be. Likely some global value being set that is causing issues.

Since `from probstructs import ExponentialCountMinSketch` being imported first causes the troubles, I am wondering if it is the suspect.

**Comment by martin-majlis** [comment]
`probstructs` - are using pybind11 - https://github.com/martin-majlis/py-probstructs/blob/master/probstructs/main.cpp
I will try it with some other library that are using pybind11 to see if this will behave in the same way.

**Comment by direvus** [comment]
FWIW I ran the test in a venv on MacOS 11.5.2 / Python 3.9.7, and did not encounter the error.

**Comment by laurent-chriqui** [comment]
Hello,

I have the same issue with the pulsar-client library using Python>=3.9. It works fine with python 3.8

When I import pulsar first, I have the exact same issue with pyproj.
If I import pulsar first, I have a bug in pyproj when I try to do this for example:

```python
import pulsar
import pyproj

pyproj.Transformer.from_crs('epsg:4326', 'epsg:3035')
```
```Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/pyproj/transformer.py", line 600, in from_crs
    cstrencode(CRS.from_user_input(crs_from).srs),
  File "/usr/local/lib/python3.9/site-packages/pyproj/crs/crs.py", line 501, in from_user_input
    return cls(value, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/pyproj/crs/crs.py", line 348, in __init__
    self._local.crs = _CRS(self.srs)
  File "pyproj/_crs.pyx", line 2352, in pyproj._crs._CRS.__init__
pyproj.exceptions.CRSError: Invalid projection: epsg:4326: (Internal Proj Error: proj_create: cannot build geodeticCRS 4326: cannot build unit of measure 9122: non double value)
```

So there seems to be some kind of conflict between cpp libraries (since pulsar is also a wrapper for their cpp library) and python 3.9+

Would really appreciate someone looking into this.
