### ISSUE TITLE
pyproj ImportError : undefined symbol: proj_context_set_ca_bundle_path

### ISSUE THREAD

**Issue by jldz9** [pyproj4/pyproj#864]
#### Code Sample, a copy-pastable example if possible

A "Minimal, Complete and Verifiable Example" will make it much easier for maintainers to help you:
http://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports

```python
 jldz9@r10smithryang:~/InSAR_Sentinel_3/Mississippi$ save_qgis.py
Traceback (most recent call last):
  File "/usr/local/home/jldz9/tools/MintPy/mintpy/save_qgis.py", line 17, in <module>
    from mintpy.utils import ptime, readfile, utils as ut
  File "/usr/local/home/jldz9/tools/MintPy/mintpy/utils/utils.py", line 24, in <module>
    from mintpy.utils.utils0 import *
  File "/usr/local/home/jldz9/tools/MintPy/mintpy/utils/utils0.py", line 23, in <module>
    from pyproj import Proj, Transformer
  File "/usr/local/home/jldz9/anaconda3/envs/mintpy/lib/python3.8/site-packages/pyproj/__init__.py", line 49, in <module>
    import pyproj.network
  File "/usr/local/home/jldz9/anaconda3/envs/mintpy/lib/python3.8/site-packages/pyproj/network.py", line 10, in <module>
    from pyproj._network import (  # noqa: F401
ImportError: /usr/local/home/jldz9/anaconda3/envs/mintpy/lib/python3.8/site-packages/pyproj/_network.cpython-38-x86_64-linux-gnu.so: undefined symbol: proj_context_set_ca_bundle_path
```
#### Problem description
Pyproj is imported by mintpy function [save_qgis.py ](https://github.com/insarlab/MintPy/blob/main/mintpy/save_qgis.py)
When I tried it out it it simply give me the import error, I opened the issue [ there ](https://github.com/insarlab/MintPy/issues/583)  but the author told me it might be the pyproj install issue. 

#### Expected Output
expect to output help page if I just simply input save_qgis.py without any parameters

#### Environment Information

 - Output from: `pyproj -v`
```
pyproj info:
    pyproj: 3.1.0
      PROJ: 7.2.0
  data dir: /usr/local/home/jldz9/anaconda3/envs/mintpy/share/proj
user_data_dir: /usr/local/home/jldz9/.local/share/proj

System:
    python: 3.8.10 | packaged by conda-forge | (default, May 11 2021, 07:01:05)  [GCC 9.3.0]
executable: /usr/local/home/jldz9/anaconda3/envs/mintpy/bin/python
   machine: Linux-5.4.0-73-generic-x86_64-with-glibc2.10

Python deps:
   certifi: 2021.05.30
       pip: 21.1.1
setuptools: 52.0.0.post20210125
    Cython: None

```

 - Output from: `python -m pyproj -v`

 - Output from: `python -c "import pyproj; pyproj.show_versions()"`

 - pyproj version (`python -c "import pyproj; print(pyproj.__version__)"`)
 - PROJ version (`python -c "import pyproj; print(pyproj.proj_version_str)"`)
 - PROJ data directory (`python -c "import pyproj; print(pyproj.datadir.get_data_dir())"`)
 - Python version (`python -c "import sys; print(sys.version.replace('\n', ' '))"`)
 - Operation System Information (`python -c "import platform; print(platform.platform())"`)

#### Installation method
 - conda, pip wheel, from source, etc...
 - conda

#### Conda environment information (if you installed with conda):

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list proj
# packages in environment at /usr/local/home/jldz9/anaconda3/envs/mintpy:
#
# Name                    Version                   Build  Channel
proj                      7.2.0                h277dcde_2    conda-forge
pyproj                    3.1.0            py38h53229fd_3    conda-forge


```
```
$conda list
(mintpy) jldz9@r10smithryang:~/InSAR_Sentinel_3/Mississippi$ conda list
# packages in environment at /usr/local/home/jldz9/anaconda3/envs/mintpy:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
alsa-lib                  1.2.3                h516909a_0    conda-forge
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
asciitree                 0.3.3                      py_2    conda-forge
blosc                     1.21.0               h9c3ff4c_0    conda-forge
bokeh                     2.3.2            py38h578d9bd_0    conda-forge
boost-cpp                 1.74.0               hc6e9bd1_3    conda-forge
brotli                    1.0.9                h9c3ff4c_4    conda-forge
brotlipy                  0.7.0           py38h497a2fe_1001    conda-forge
brunsli                   0.1                  h9c3ff4c_0    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.17.1               h7f98852_1    conda-forge
ca-certificates           2021.5.30            ha878542_0    conda-forge
cairo                     1.16.0            h6cf1ce9_1008    conda-forge
cartopy                   0.19.0.post1     py38hc9c980b_0    conda-forge
cdsapi                    0.5.1              pyhd8ed1ab_0    conda-forge
certifi                   2021.5.30        py38h578d9bd_0    conda-forge
cffi                      1.14.5           py38ha65f79e_0    conda-forge
cfitsio                   3.470                hb418390_7    conda-forge
cftime                    1.5.0            py38hb5d20a5_0    conda-forge
chardet                   4.0.0            py38h578d9bd_1    conda-forge
charls                    2.2.0                h9c3ff4c_0    conda-forge
click                     8.0.1            py38h578d9bd_0    conda-forge
cloudpickle               1.6.0                      py_0    conda-forge
configobj                 5.0.6                      py_0    conda-forge
cryptography              3.4.7            py38ha5dfef3_0    conda-forge
curl                      7.77.0               hea6ffbf_0    conda-forge
cvxopt                    1.2.6            py38h55e5319_0    conda-forge
cycler                    0.10.0                     py_2    conda-forge
cytoolz                   0.11.0           py38h497a2fe_3    conda-forge
dask                      2021.6.2           pyhd8ed1ab_0    conda-forge
dask-core                 2021.6.2           pyhd8ed1ab_0    conda-forge
dask-jobqueue             0.7.2              pyhd8ed1ab_1    conda-forge
dbus                      1.13.6               h48d8840_2    conda-forge
decorator                 5.0.9              pyhd8ed1ab_0    conda-forge
defusedxml                0.7.1              pyhd8ed1ab_0    conda-forge
distributed               2021.6.2         py38h578d9bd_0    conda-forge
dsdp                      5.8               hd9d9efa_1203    conda-forge
eccodes                   2.21.0               ha0e6eb6_0    conda-forge
expat                     2.4.1                h9c3ff4c_0    conda-forge
fasteners                 0.16               pyhd8ed1ab_0    conda-forge
fftw                      3.3.9           nompi_h74d3f13_101    conda-forge
fontconfig                2.13.1            hba837de_1005    conda-forge
freetype                  2.10.4               h0708190_1    conda-forge
freexl                    1.0.6                h7f98852_0    conda-forge
fsspec                    2021.6.1           pyhd8ed1ab_0    conda-forge
gdal                      3.2.1            py38hc0b2d6b_7    conda-forge
geos                      3.9.1                h9c3ff4c_2    conda-forge
geotiff                   1.6.0                h2b14fbe_4    conda-forge
gettext                   0.19.8.1          h0b5b191_1005    conda-forge
giflib                    5.2.1                h36c2ea0_2    conda-forge
glib                      2.68.3               h9c3ff4c_0    conda-forge
glib-tools                2.68.3               h9c3ff4c_0    conda-forge
glpk                      4.65              h9202a9a_1004    conda-forge
gmp                       6.2.1                h58526e2_0    conda-forge
gsl                       2.6                  he838d99_2    conda-forge
gst-plugins-base          1.18.4               hf529b03_2    conda-forge
gstreamer                 1.18.4               h76c114f_2    conda-forge
h5py                      2.10.0          nompi_py38h9915d05_106    conda-forge
hdf4                      4.2.15               h10796ff_3    conda-forge
hdf5                      1.10.6          nompi_h6a2412b_1114    conda-forge
heapdict                  1.0.1                      py_0    conda-forge
icu                       68.1                 h58526e2_0    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
imagecodecs               2021.3.31        py38h1455ab2_0    conda-forge
imageio                   2.9.0                      py_0    conda-forge
jasper                    1.900.1           h07fcdf6_1006    conda-forge
jinja2                    3.0.1              pyhd8ed1ab_0    conda-forge
jpeg                      9d                   h36c2ea0_0    conda-forge
json-c                    0.15                 h98cffda_0    conda-forge
jxrlib                    1.1                  h7f98852_2    conda-forge
kealib                    1.4.14               hcc255d8_2    conda-forge
kiwisolver                1.3.1            py38h1fd1430_1    conda-forge
krb5                      1.19.1               hcc1bbae_0    conda-forge
lcms2                     2.12                 hddcbb42_0    conda-forge
ld_impl_linux-64          2.35.1               hea4e1c9_2    conda-forge
lerc                      2.2.1                h9c3ff4c_0    conda-forge
libaec                    1.0.5                h9c3ff4c_0    conda-forge
libblas                   3.9.0                9_openblas    conda-forge
libcblas                  3.9.0                9_openblas    conda-forge
libclang                  11.1.0          default_ha53f305_1    conda-forge
libcurl                   7.77.0               h2574ce0_0    conda-forge
libdap4                   3.20.6               hd7c4107_2    conda-forge
libdeflate                1.7                  h7f98852_5    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libevent                  2.1.10               hcdb4288_3    conda-forge
libffi                    3.3                  h58526e2_2    conda-forge
libgcc-ng                 9.3.0               h2828fa1_19    conda-forge
libgdal                   3.2.1                h38ff51b_7    conda-forge
libgfortran-ng            9.3.0               hff62375_19    conda-forge
libgfortran5              9.3.0               hff62375_19    conda-forge
libglib                   2.68.3               h3e27bee_0    conda-forge
libgomp                   9.3.0               h2828fa1_19    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
libkml                    1.3.0             h238a007_1013    conda-forge
liblapack                 3.9.0                9_openblas    conda-forge
libllvm11                 11.1.0               hf817b99_2    conda-forge
libnetcdf                 4.7.4           nompi_h56d31a8_107    conda-forge
libnghttp2                1.43.0               h812cca2_0    conda-forge
libogg                    1.3.4                h7f98852_1    conda-forge
libopenblas               0.3.15          pthreads_h8fe5266_1    conda-forge
libopus                   1.3.1                h7f98852_1    conda-forge
libpng                    1.6.37               h21135ba_2    conda-forge
libpq                     13.3                 hd57d9b9_0    conda-forge
librttopo                 1.1.0                h1185371_6    conda-forge
libspatialite             5.0.1                he52d314_3    conda-forge
libssh2                   1.9.0                ha56f1ee_6    conda-forge
libstdcxx-ng              9.3.0               h6de172a_19    conda-forge
libtiff                   4.2.0                hbd63e13_2    conda-forge
libuuid                   2.32.1            h7f98852_1000    conda-forge
libvorbis                 1.3.7                h9c3ff4c_0    conda-forge
libwebp-base              1.2.0                h7f98852_2    conda-forge
libxcb                    1.13              h7f98852_1003    conda-forge
libxkbcommon              1.0.3                he3ba5ed_0    conda-forge
libxml2                   2.9.12               h72842e0_0    conda-forge
libxslt                   1.1.33               h15afd5d_2    conda-forge
libzopfli                 1.0.3                h9c3ff4c_0    conda-forge
llvm-openmp               8.0.1                hc9558a2_0    conda-forge
locket                    0.2.0                      py_2    conda-forge
lxml                      4.6.3            py38hf1fe3a4_0    conda-forge
lz4-c                     1.9.3                h9c3ff4c_0    conda-forge
markupsafe                2.0.1            py38h497a2fe_0    conda-forge
matplotlib                3.4.2            py38h578d9bd_0    conda-forge
matplotlib-base           3.4.2            py38hcc49a3a_0    conda-forge
metis                     5.1.0             h58526e2_1006    conda-forge
monotonic                 1.5                        py_0    conda-forge
mpfr                      4.0.2                he80fd80_1    conda-forge
msgpack-python            1.0.2            py38h1fd1430_1    conda-forge
mysql-common              8.0.25               ha770c72_0    conda-forge
mysql-libs                8.0.25               h935591d_0    conda-forge
ncurses                   6.2                  h58526e2_4    conda-forge
netcdf4                   1.5.6           nompi_py38hf887595_102    conda-forge
networkx                  2.5                        py_0    conda-forge
nspr                      4.30                 h9c3ff4c_0    conda-forge
nss                       3.67                 hb5efdd6_0    conda-forge
numcodecs                 0.7.3            py38h709712a_0    conda-forge
numpy                     1.21.0           py38h9894fe3_0    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openjpeg                  2.4.0                hb52868f_1    conda-forge
openmp                    8.0.1                         0    conda-forge
openssl                   1.1.1k               h7f98852_0    conda-forge
packaging                 20.9               pyh44b312d_0    conda-forge
pandas                    1.2.5            py38h1abd341_0    conda-forge
partd                     1.2.0              pyhd8ed1ab_0    conda-forge
pcre                      8.45                 h9c3ff4c_0    conda-forge
pillow                    8.2.0            py38ha0e1e83_1    conda-forge
pip                       21.1.2             pyhd8ed1ab_0    conda-forge
pixman                    0.40.0               h36c2ea0_0    conda-forge
pooch                     1.4.0              pyhd8ed1ab_0    conda-forge
poppler                   0.89.0               h2de54a5_5    conda-forge
poppler-data              0.4.10                        0    conda-forge
postgresql                13.3                 h2510834_0    conda-forge
proj                      7.2.0                h277dcde_2    conda-forge
psutil                    5.8.0            py38h497a2fe_1    conda-forge
pthread-stubs             0.4               h36c2ea0_1001    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pygrib                    2.1.3            py38h549f6ee_0    conda-forge
pyhdf                     0.10.3           py38he643327_0    conda-forge
pykdtree                  1.3.4            py38h0b5ebd8_0    conda-forge
pykml                     0.2.0                    pypi_0    pypi
pyopenssl                 20.0.1             pyhd8ed1ab_0    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyproj                    3.1.0            py38h53229fd_3    conda-forge
pyqt                      5.12.3           py38h578d9bd_7    conda-forge
pyqt-impl                 5.12.3           py38h7400c14_7    conda-forge
pyqt5-sip                 4.19.18          py38h709712a_7    conda-forge
pyqtchart                 5.12             py38h7400c14_7    conda-forge
pyqtwebengine             5.12.1           py38h7400c14_7    conda-forge
pyresample                1.20.0           py38h1abd341_0    conda-forge
pyshp                     2.1.3              pyh44b312d_0    conda-forge
pysocks                   1.7.1            py38h578d9bd_3    conda-forge
pysolid                   0.1.2                    pypi_0    pypi
python                    3.8.10          h49503c6_1_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python_abi                3.8                      2_cp38    conda-forge
pytz                      2021.1             pyhd8ed1ab_0    conda-forge
pywavelets                1.1.1            py38h5c078b8_3    conda-forge
pyyaml                    5.4.1            py38h497a2fe_0    conda-forge
qt                        5.12.9               hda022c4_4    conda-forge
readline                  8.1                  h46c0cb4_0    conda-forge
requests                  2.25.1             pyhd3deb0d_0    conda-forge
scikit-image              0.18.1           py38h51da96c_0    conda-forge
scipy                     1.6.3            py38h7b17777_0    conda-forge
setuptools                49.6.0           py38h578d9bd_3    conda-forge
shapely                   1.7.1            py38haeee4fe_5    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
snappy                    1.1.8                he1b5a44_3    conda-forge
sortedcontainers          2.4.0              pyhd8ed1ab_0    conda-forge
sqlite                    3.36.0               h9cd32fc_0    conda-forge
suitesparse               5.10.1               hd8046ac_0    conda-forge
tbb                       2020.2               h4bd325d_4    conda-forge
tblib                     1.7.0              pyhd8ed1ab_0    conda-forge
tifffile                  2021.4.8           pyhd8ed1ab_0    conda-forge
tiledb                    2.2.9                h91fcb0e_0    conda-forge
tk                        8.6.10               h21135ba_1    conda-forge
toolz                     0.11.1                     py_0    conda-forge
tornado                   6.1              py38h497a2fe_1    conda-forge
tqdm                      4.61.1             pyhd8ed1ab_0    conda-forge
typing_extensions         3.10.0.0           pyha770c72_0    conda-forge
tzcode                    2021a                h7f98852_1    conda-forge
tzdata                    2021a                he74cb21_0    conda-forge
urllib3                   1.26.5             pyhd8ed1ab_0    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
xarray                    0.18.2             pyhd8ed1ab_0    conda-forge
xerces-c                  3.2.3                h9d8b166_2    conda-forge
xorg-kbproto              1.0.7             h7f98852_1002    conda-forge
xorg-libice               1.0.10               h7f98852_0    conda-forge
xorg-libsm                1.2.3             hd9c2040_1000    conda-forge
xorg-libx11               1.7.2                h7f98852_0    conda-forge
xorg-libxau               1.0.9                h7f98852_0    conda-forge
xorg-libxdmcp             1.1.3                h7f98852_0    conda-forge
xorg-libxext              1.3.4                h7f98852_1    conda-forge
xorg-libxrender           0.9.10            h7f98852_1003    conda-forge
xorg-renderproto          0.11.1            h7f98852_1002    conda-forge
xorg-xextproto            7.3.0             h7f98852_1002    conda-forge
xorg-xproto               7.0.31            h7f98852_1007    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
yaml                      0.2.5                h516909a_0    conda-forge
zarr                      2.8.3              pyhd8ed1ab_0    conda-forge
zfp                       0.5.5                h9c3ff4c_5    conda-forge
zict                      2.0.0                      py_0    conda-forge
zlib                      1.2.11            h516909a_1010    conda-forge
zstd                      1.4.9                ha95c52a_0    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
(mintpy) jldz9@r10smithryang:~/InSAR_Sentinel_3/Mississippi$ conda info

     active environment : mintpy
    active env location : /usr/local/home/jldz9/anaconda3/envs/mintpy
            shell level : 2
       user config file : /usr/local/home/jldz9/.condarc
 populated config files :
          conda version : 4.10.1
    conda-build version : 3.21.4
         python version : 3.8.8.final.0
       virtual packages : __cuda=9.1=0
                          __linux=5.4.0=0
                          __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /usr/local/home/jldz9/anaconda3  (writable)
      conda av data dir : /usr/local/home/jldz9/anaconda3/etc/conda
  conda av metadata url : https://repo.anaconda.com/pkgs/main
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /usr/local/home/jldz9/anaconda3/pkgs
                          /usr/local/home/jldz9/.conda/pkgs
       envs directories : /usr/local/home/jldz9/anaconda3/envs
                          /usr/local/home/jldz9/.conda/envs
               platform : linux-64
             user-agent : conda/4.10.1 requests/2.25.1 CPython/3.8.8 Linux/5.4.0-73-generic ubuntu/20.04.2 glibc/2.31
                UID:GID : 73268:5513
             netrc file : /usr/local/home/jldz9/.netrc
           offline mode : False

```
</details>

**Comment by snowman2** [comment]
@jldz9 I would recommend re-creating your conda environment. Whenever I see the undefined symbol error, it usually indicates that pyproj was built against a different version of PROJ than it is running against.

**Comment by snowman2** [comment]
I am going to recommend re-creating your environment and ensuring that you use `conda activate <envonment name>` before use. If that does not solve your issue, I recommend raising an issue here: https://github.com/conda-forge/pyproj-feedstock/
