### ISSUE TITLE
python setup.py egg_info

### ISSUE THREAD

**Issue by crack00r** [pyproj4/pyproj#89]
i have installed Visual Studio COmmunity, but still get this error, may any help?

C:\Users\Manuel\Desktop>pip install pyproj-1.9.5.1.tar.gz
Processing c:\users\manuel\desktop\pyproj-1.9.5.1.tar.gz
    Complete output from command python setup.py egg_info:
    using bundled proj4..
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\manuel\appdata\local\temp\pip-m2wkql-build\setup.py", line 72, in <module>
        objects = cc.compile(['nad2bin.c', 'src/pj_malloc.c'])
      File "c:\python27\lib\distutils\msvc9compiler.py", line 473, in compile
        self.initialize()
      File "c:\python27\lib\distutils\msvc9compiler.py", line 383, in initialize
        vc_env = query_vcvarsall(VERSION, plat_spec)
      File "c:\python27\lib\site-packages\setuptools\msvc.py", line 172, in msvc9_query_vcvarsall
        return EnvironmentInfo(arch, ver).return_env()
      File "c:\python27\lib\site-packages\setuptools\msvc.py", line 1102, in return_env
        [self.VCIncludes,
      File "c:\python27\lib\site-packages\setuptools\msvc.py", line 810, in VCIncludes
        return [os.path.join(self.si.VCInstallDir, 'Include'),
      File "c:\python27\lib\site-packages\setuptools\msvc.py", line 540, in VCInstallDir
        python_vc = self.ri.lookup(reg_path, 'installdir')
      File "c:\python27\lib\site-packages\setuptools\msvc.py", line 450, in lookup
        bkey = winreg.OpenKey(hkey, key, 0, winreg.KEY_READ)
    WindowsError: [Error 2] Das System kann die angegebene Datei nicht finden

```
----------------------------------------
```

Command "python setup.py egg_info" failed with error code 1 in c:\users\manuel\appdata\local\temp\pip-m2wkql-build\

C:\Users\Manuel\Desktop>

**Comment by micahcochran** [comment]
Visual Studio Community Edition and Python 2.7 most likely won't work together.  In Windows, the Python version has to match the Microsoft compiler version used to compile that version of Python.  For Python 2.7 is Microsoft Visual C++ 9.0.  (I don't think they ever made a version 9.0 [or Visual Studio 2008] Community Edition.)

Try installing this [Microsoft Visual C++ Compiler for Python 2.7](https://www.microsoft.com/en-us/download/details.aspx?id=44266).

**Comment by snowman2** [comment]
Refer to #216
