### ISSUE TITLE
Transformer.from_pipeline(wkt or json str) does not work with always_xy=True

### ISSUE THREAD

**Issue by skogler** [pyproj4/pyproj#967]
#### Code Sample

```python
Transformer.from_pipeline(Transformer.from_crs(4326, 3857, always_xy=True).to_wkt())
```

#### Problem description

Decoding WKT or PROJJSON coordinate transformations is broken if `always_xy=True`.

The generated WKT is (not sure if its valid):

```wkt
CONCATENATEDOPERATION["axis order change (2D) + Popular Visualisation Pseudo-Mercator",
    SOURCECRS[
        GEOGCRS["WGS 84 (with axis order normalized for visualization)",
            ENSEMBLE["World Geodetic System 1984 ensemble",
                MEMBER["World Geodetic System 1984 (Transit)",
                    ID["EPSG",1166]],
                MEMBER["World Geodetic System 1984 (G730)",
                    ID["EPSG",1152]],
                MEMBER["World Geodetic System 1984 (G873)",
                    ID["EPSG",1153]],
                MEMBER["World Geodetic System 1984 (G1150)",
                    ID["EPSG",1154]],
                MEMBER["World Geodetic System 1984 (G1674)",
                    ID["EPSG",1155]],
                MEMBER["World Geodetic System 1984 (G1762)",
                    ID["EPSG",1156]],
                ELLIPSOID["WGS 84",6378137,298.257223563,
                    LENGTHUNIT["metre",1],
                    ID["EPSG",7030]],
                ENSEMBLEACCURACY[2.0],
                ID["EPSG",6326]],
            PRIMEM["Greenwich",0,
                ANGLEUNIT["degree",0.0174532925199433],
                ID["EPSG",8901]],
            CS[ellipsoidal,2],
                AXIS["geodetic longitude (Lon)",east,
                    ORDER[1],
                    ANGLEUNIT["degree",0.0174532925199433,
                        ID["EPSG",9122]]],
                AXIS["geodetic latitude (Lat)",north,
                    ORDER[2],
                    ANGLEUNIT["degree",0.0174532925199433,
                        ID["EPSG",9122]]],
            REMARK["Axis order reversed compared to EPSG:4326"]]],
    TARGETCRS[
        PROJCRS["WGS 84 / Pseudo-Mercator",
            BASEGEOGCRS["WGS 84",
                ENSEMBLE["World Geodetic System 1984 ensemble",
                    MEMBER["World Geodetic System 1984 (Transit)"],
                    MEMBER["World Geodetic System 1984 (G730)"],
                    MEMBER["World Geodetic System 1984 (G873)"],
                    MEMBER["World Geodetic System 1984 (G1150)"],
                    MEMBER["World Geodetic System 1984 (G1674)"],
                    MEMBER["World Geodetic System 1984 (G1762)"],
                    ELLIPSOID["WGS 84",6378137,298.257223563,
                        LENGTHUNIT["metre",1]],
                    ENSEMBLEACCURACY[2.0]],
                PRIMEM["Greenwich",0,
                    ANGLEUNIT["degree",0.0174532925199433]],
                ID["EPSG",4326]],
            CONVERSION["Popular Visualisation Pseudo-Mercator",
                METHOD["Popular Visualisation Pseudo Mercator",
                    ID["EPSG",1024]],
                PARAMETER["Latitude of natural origin",0,
                    ANGLEUNIT["degree",0.0174532925199433],
                    ID["EPSG",8801]],
                PARAMETER["Longitude of natural origin",0,
                    ANGLEUNIT["degree",0.0174532925199433],
                    ID["EPSG",8802]],
                PARAMETER["False easting",0,
                    LENGTHUNIT["metre",1],
                    ID["EPSG",8806]],
                PARAMETER["False northing",0,
                    LENGTHUNIT["metre",1],
                    ID["EPSG",8807]]],
            CS[Cartesian,2],
                AXIS["easting (X)",east,
                    ORDER[1],
                    LENGTHUNIT["metre",1]],
                AXIS["northing (Y)",north,
                    ORDER[2],
                    LENGTHUNIT["metre",1]],
            ID["EPSG",3857]]],
    STEP[
        CONVERSION["axis order change (2D)",
            METHOD["Axis Order Reversal (2D)",
                ID["EPSG",9843]],
            ID["EPSG",15498]]],
    STEP[
        CONVERSION["Popular Visualisation Pseudo-Mercator",
            METHOD["Popular Visualisation Pseudo Mercator",
                ID["EPSG",1024]],
            PARAMETER["Latitude of natural origin",0,
                ANGLEUNIT["degree",0.0174532925199433],
                ID["EPSG",8801]],
            PARAMETER["Longitude of natural origin",0,
                ANGLEUNIT["degree",0.0174532925199433],
                ID["EPSG",8802]],
            PARAMETER["False easting",0,
                LENGTHUNIT["metre",1],
                ID["EPSG",8806]],
            PARAMETER["False northing",0,
                LENGTHUNIT["metre",1],
                ID["EPSG",8807]],
            ID["EPSG",3856]]],
    USAGE[
        SCOPE["unknown"],
        AREA["World"],
        BBOX[-90,-180,90,180]]]
```

#### Expected Output

I would expect pyproj to be able to decode the WKT/JSON it produces.

#### Environment Information

```
pyproj info:
    pyproj: 3.2.1
      PROJ: 7.2.1
  data dir: /usr/share/proj
user_data_dir: /root/.local/share/proj

System:
    python: 3.8.10 (default, Jun  2 2021, 10:49:15)  [GCC 9.4.0]
executable: /usr/bin/python3
   machine: Linux-5.11.0-37-generic-x86_64-with-glibc2.29

Python deps:
   certifi: 2021.05.30
       pip: 21.2.4
setuptools: 45.2.0
    Cython: None
```
#### Installation method

 - wheel built from source against proj 7.2.1 on ubuntu 20.04-based docker image.

**Comment by snowman2** [comment]
Can you try with the latest PROJ (8.1.1)?

**Comment by skogler** [comment]
Just tried with the latest version from PyPI, the behaviour is identical:
```
from pyproj import *
pyproj.show_versions()
pyproj info:
    pyproj: 3.2.1
      PROJ: 8.1.1
  data dir: /home/skogler/.cache/pypoetry/virtualenvs/scripts-JQ2wa0c_-py3.9/lib/python3.9/site-packages/pyproj/proj_dir/share/proj
user_data_dir: /home/skogler/.local/share/proj
System:
    python: 3.9.5 (default, May 11 2021, 08:20:37)  [GCC 10.3.0]
executable: /home/skogler/.cache/pypoetry/virtualenvs/scripts-JQ2wa0c_-py3.9/bin/python
   machine: Linux-5.11.0-37-generic-x86_64-with-glibc2.33
Python deps:
   certifi: 2021.05.30
       pip: 21.2.2
setuptools: 57.4.0
    Cython: None
Transformer.from_pipeline(Transformer.from_crs(4326, 3857, always_xy=True).to_wkt())
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/skogler/.cache/pypoetry/virtualenvs/scripts-JQ2wa0c_-py3.9/lib/python3.9/site-packages/pyproj/transformer.py", line 577, in from_pipeline
    return Transformer(TransformerFromPipeline(cstrencode(proj_pipeline)))
  File "/home/skogler/.cache/pypoetry/virtualenvs/scripts-JQ2wa0c_-py3.9/lib/python3.9/site-packages/pyproj/transformer.py", line 310, in __init__
    self._local.transformer = transformer_maker()
  File "/home/skogler/.cache/pypoetry/virtualenvs/scripts-JQ2wa0c_-py3.9/lib/python3.9/site-packages/pyproj/transformer.py", line 124, in __call__
    return _Transformer.from_pipeline(self.proj_pipeline)
  File "pyproj/_transformer.pyx", line 696, in pyproj._transformer._Transformer.from_pipeline
pyproj.exceptions.ProjError: Invalid projection CONCATENATEDOPERATION["axis order change (2D) + Popular Visualisation Pseudo-Mercator",SOURCECRS[GEOGCRS["WGS 84 (with axis order normalized for visualization)",ENSEMBLE["World Geodetic System 1984 ensemble",MEMBER["World Geodetic System 1984 (Transit)",ID["EPSG",1166]],MEMBER["World Geodetic System 1984 (G730)",ID["EPSG",1152]],MEMBER["World Geodetic System 1984 (G873)",ID["EPSG",1153]],MEMBER["World Geodetic System 1984 (G1150)",ID["EPSG",1154]],MEMBER["World Geodetic System 1984 (G1674)",ID["EPSG",1155]],MEMBER["World Geodetic System 1984 (G1762)",ID["EPSG",1156]],ELLIPSOID["WGS 84",6378137,298.257223563,LENGTHUNIT["metre",1],ID["EPSG",7030]],ENSEMBLEACCURACY[2.0],ID["EPSG",6326]],PRIMEM["Greenwich",0,ANGLEUNIT["degree",0.0174532925199433],ID["EPSG",8901]],CS[ellipsoidal,2],AXIS["geodetic longitude (Lon)",east,ORDER[1],ANGLEUNIT["degree",0.0174532925199433,ID["EPSG",9122]]],AXIS["geodetic latitude (Lat)",north,ORDER[2],ANGLEUNIT["degree",0.0174532925199433,ID["EPSG",9122]]],REMARK["Axis order reversed compared to EPSG:4326"]]],TARGETCRS[PROJCRS["WGS 84 / Pseudo-Mercator",BASEGEOGCRS["WGS 84",ENSEMBLE["World Geodetic System 1984 ensemble",MEMBER["World Geodetic System 1984 (Transit)"],MEMBER["World Geodetic System 1984 (G730)"],MEMBER["World Geodetic System 1984 (G873)"],MEMBER["World Geodetic System 1984 (G1150)"],MEMBER["World Geodetic System 1984 (G1674)"],MEMBER["World Geodetic System 1984 (G1762)"],ELLIPSOID["WGS 84",6378137,298.257223563,LENGTHUNIT["metre",1]],ENSEMBLEACCURACY[2.0]],PRIMEM["Greenwich",0,ANGLEUNIT["degree",0.0174532925199433]],ID["EPSG",4326]],CONVERSION["Popular Visualisation Pseudo-Mercator",METHOD["Popular Visualisation Pseudo Mercator",ID["EPSG",1024]],PARAMETER["Latitude of natural origin",0,ANGLEUNIT["degree",0.0174532925199433],ID["EPSG",8801]],PARAMETER["Longitude of natural origin",0,ANGLEUNIT["degree",0.0174532925199433],ID["EPSG",8802]],PARAMETER["False easting",0,LENGTHUNIT["metre",1],ID["EPSG",8806]],PARAMETER["False northing",0,LENGTHUNIT["metre",1],ID["EPSG",8807]]],CS[Cartesian,2],AXIS["easting (X)",east,ORDER[1],LENGTHUNIT["metre",1]],AXIS["northing (Y)",north,ORDER[2],LENGTHUNIT["metre",1]],ID["EPSG",3857]]],STEP[CONVERSION["axis order change (2D)",METHOD["Axis Order Reversal (2D)",ID["EPSG",9843]],ID["EPSG",15498]]],STEP[CONVERSION["Popular Visualisation Pseudo-Mercator",METHOD["Popular Visualisation Pseudo Mercator",ID["EPSG",1024]],PARAMETER["Latitude of natural origin",0,ANGLEUNIT["degree",0.0174532925199433],ID["EPSG",8801]],PARAMETER["Longitude of natural origin",0,ANGLEUNIT["degree",0.0174532925199433],ID["EPSG",8802]],PARAMETER["False easting",0,LENGTHUNIT["metre",1],ID["EPSG",8806]],PARAMETER["False northing",0,LENGTHUNIT["metre",1],ID["EPSG",8807]],ID["EPSG",3856]]],USAGE[SCOPE["unknown"],AREA["World"],BBOX[-90,-180,90,180]]].: (Internal Proj Error: proj_create: Cannot build concatenated operation: At least one of the operation lacks a source and/or target CRS)
```
